### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/in-game#1]
@6r1d I pushed voting computer luac to this repo, as you wrote large part of it you should also give some opinion for license, hopefully I did not already violate your terms :rofl:

This might seem like something that is not needed at all but problem is that without license there's also no rights to use published work at all so without license there's no sharing. I'd recommend adding permissive license for repo and just require all things in repo to be licensed with selected permissive license.

Having another license for whatever stuff you push here (as long as it is your work) does not create license conflicts as copyright holder decides what licenses or terms to allow. Pushing to this repo would simply add another permissive license for that piece.

I would like simple and permissive solution and go with MIT license.

**Comment by 6r1d** [comment]
MIT license works for me, @S-S-X. I'm happy there's some use for this code. :-)

**Comment by S-S-X** [comment]
Noticed that there was nicely attributed small piece of work copyrighted by CC-BY-SA 3.0 which is restrictive and is incompatible with MIT license which is permissive.
However this use case / copied work probably wont even fulfill "sweat of the brow" or "originality" requirements for copyrighted work so I don't think that content really causes any license conflicts here.
