### ISSUE TITLE
Slower starvation 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#101]
ThinkSome
Why do we start losing health already when stamina < 4? or <5?

SX
You wont start losing health if resting, only if doing something but maybe that should be updated to lose health only after saturation is less than or equal to starve_lvl which is 3 by default.

SX
saturation <= stamina.settings.starve_lvl. Maybe it was saturation < stamina.settings.starve_lvl before... so it is now 1 point higher..

ThinkSome
Why not set starve level to 1 or 0? That would give us more flexibility in foods, as right now foods that give>12 stamina are not worth it.

SX
Maybe because there's other things happening and I could imagine more dynamic starving instead of simple remove 1 hp when below <insert some static number>.
Gives idea about starting very slow starving and hp removal bit earlier but make it be current 1 / second a lot later like maybe when already at 0 instead of current...

ThinkSome
I don't think we should starve at all when there are still breads remaining.

SX
That would make many of possible (cheap in terms of performance) improvements harder using current code, maybe CSM can rescale it to display 0 when value is at 4?

ThinkSome
It can rescale, but that does not change server-side behaviour. The problem is as stated above, that the current starve_level makes foods that give >12 breads a waste of time (assuming they are harder to prepare than 12 bread ones).

SX
You can use pickled food to get more or some other that gives better balance for your use case, I like current because it is good balance for running. But check < instead of <= should be fixed as now it is different for event based and globalstep based. Even while just 1 point it still is inconsistent.

Also I don't think few points would really affect actually active players as they have other things to think than exact time when to eat some exactly balanced amount of perfect food

Huhhila
Looks like compass jumps like 0.2 too high... which is semi-bad from beowulf perspective. Would lower increase risk of falling before area is loaded?

SX
Huhhila, similar rounding problem also with unified inventory waypoints...
One of those can live with but would be nice to fix things...

SX
Testing and not losing health yet being active when saturation at 4 points...
Started losing health when saturation at 3 points which is correct or should it be 1 less? 2 points would be 1 full bread icon left.

**Comment by OgelGames** [comment]
https://github.com/S-S-X/stamina/blob/fc8c7157b16139b0624d8a911bedcc9ad48ed06e/init.lua#L391
