### ISSUE TITLE
Temporary XP donation to new players  

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#102]
specing
Idea: donating XP. Say you've got a friend that wants to help you build your Mars base, but they don't have the XP to get there.
The only current option is to make an account for them and grind it to 50k or tell them to grind to 50k (and be told to get lost xD).

wsor 
no one has made afk xp farms?  Seems perfect thing to automate.

specing 
I did it, but farming XP wasn't the intention.

Maybe XP loans for those would would find it harder to part with their XP? Loan someone 50k XP for a day :) The loan is removed a few minutes after either you or the person you are loaning to logs off. 

SX
Idea behind xp is basically to force players new to pandorabox actually do some things before being able to do more, some players used to do just that: get xp asap shoveling sand / building nerdpiles (aka cobble-stone pillars). Then they're totally lost without any idea how things actually work on pandorabox (and this is somewhat experienced mt players).

specing
I thought about that and hence the XP loan idea. They have to both be online, so the experienced player is there to babysit.

Hedgehog
IMO, harvesting trees manually gives the most XP.   A decently sized giant sequoia can easily net you 2500 XP. Just takes a while to do so.

**Comment by OgelGames** [comment]
I believe the moon/mars access privs can be granted by admin regardless of XP, perhaps it could be made so staff could temporarily grant those to players? (revoked after a certain time)

**Comment by S-S-X** [comment]
I think granting early permissions like that would not really be fair, most players are fine with it and willing to actually do something to gain access privileges.

Also getting moon access is not really that much work. After you've built basic things like farm, house and some things that makes you established player you already have enough XP for Moon access.

If player is not willing to work at all and access it about direct access to resources and it would actually be considered to allow granting privileges before reaching required XP level then it would be better to just get rid of XP requirements completely but that also is not good in my opinion as it is part of game progression, something to achieve.
Giving this for free for some players would be really unfair for others.
