### ISSUE TITLE
Spawn Fly Beacon 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#103]
PhrogMan
Add fly beacon at spawn although many things can go wrong with that.
1- People may think that you could fly everywhere.
2- A lot more would be jumping off of spawn.

Test_User
I've jumped off spawn and survived several times.

Hedgehog
Can't we place a bunch of trampolines below spawn?

Test_User
Trampolines still hurt when you fall fast enough. Otherwise, that would be fun.

**Comment by OgelGames** [comment]
AFAIK, it was decided when spawn was built that there would be no fly beacon there, and I don't think there's any reason to add one now.
