### ISSUE TITLE
Request recipe: LV/MV/HV Cable Plate direct upgrade to Digi Cable Plate

### ISSUE THREAD

**Issue by eshattow** [pandorabox-io/in-game#104]
Can we add a recipe for technic mixing:

 LV Cable Plate (1) + Digimese (5) --> LV Digi Cable Plate (1)
 MV Cable Plate (1) + Digimese (5) --> MV Digi Cable Plate (1)
 HV Cable Plate (1) + Digimese (5) --> HV Digi Cable Plate (1)

Reason:

Several items allow to be upgraded to digiline versions by mixing. It seems that Digi Cable Plate is just missing some recipe to do this.

**Comment by S-S-X** [comment]
Exact same recipe used to craft digi cable but with cable plate as input in place of normal cable for crafting makes sense.
Would be good to also fix description for digi cables if adding recipes, broken descriptions was just simple mistake.

Reworking cable plates to not be different nodes would also make sense...

**Comment by eshattow** [comment]
Commit mt-mods/technic@b659774 looks good to me if using digistuff mod. Otherwise I think there is some break in parity for the recipe without the digistuff mod enabled, but that is not an issue for pandorabox where the digistuff mod is enabled.
