### ISSUE TITLE
Introducing bug command / linking #reports to in-game

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#109]
specing
There is a server that has a /bug command, maybe it could also be useful here?
(for reporting bugs) And /mail can be used to amend (works together with self-hosted git?)

Hedgehog 
Isn't the #reports channel for sending in bug reports?
SX 
It is for whatever reports (report problems with players or bugs)

AceRichman 
But can only be used from discord though. Also the channel doesn't even exist in-game.

**Comment by S-S-X** [comment]
As few alternatives there's currently available:
* GitHub issue tracker
* Discord #reports channel
* /mail command

> There is a server that has a /bug command, maybe it could also be useful here?

What is exact function of this command? I mean what would happen when you use it in game?

> (works together with self-hosted git?)

Self hosted git is bad solution, there's countless examples of that (some minetest communities with self hosted issue trackers and git services).
Community managed git services also do have a lot of problems. In my opinion a lot better option is to use what companies like GitHub or GitLab offer.

Is there something available that would already work together with GitHub which is currently used and probably main git service used in future?

**Comment by OgelGames** [comment]
I think we could close this by just linking #reports to in-game, I see no reason to add anything more complex than that.

**Comment by Klaranth** [comment]
Or, people post a bug in #ideas, and add the BUG prefix to it.
