### ISSUE TITLE
Admin shop price reduction at 600K XP 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#11]
Hedgehog:
Would be kinda interesting if at 600K XP all prices at admin shop is down by 25% ...
But I doubt by then you even WANT to or NEED to have the admin shop.

1hit: 
Many video games follow this pattern: You get some nice reward only after you no longer need it.  Its frustrating and in general lowers game enjoyment.  IMHO, we should avoid such things on pandorabox.

**Comment by BuckarooBanzay** [comment]
>  Would be kinda interesting if at 600K XP all prices at admin shop is down by 25% ...

IMO: this isn't really fair, also: high-level players could re-sell from the admin-shop and gain even more money...

**Comment by OgelGames** [comment]
Closing as per Buckaroo's comment.
