### ISSUE TITLE
Re-enable armor set bonuses?

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#113]
Huhhila
Should we re-enable armor set bonuses and/or rebalance lower end armors in some other way? See https://github.com/minetest-mods/3d_armor/pull/41

Benefit would be slightly more interesting mechanics for noobs, mainly. Not much difference for those who keep hazmat suit on anyway.

Hedgehog
If a new type of tool/armor would be introduced, would that throw the whole idea out of the window?

Huhhila
The set bonus is existing code that was actually in use before it got refactored in to settings...

Hedgehog
At which level , XP wise, would those mechanics become less useful?

SX 
Yes and no. 
No for "At which level , XP wise, would those mechanics become less useful?" and yes for armor set bonus.

Also would still like to add one 'but': but only after actually checking how it affects armors, currently all "top tier" armors are overpowered immortality things.
Could try if some fine tuning could be made while adding that so that current max protection can be achieved only if using full set so that mixed armor set would be reduced if needed to achieve current max only with full set bonus.
That would add some dynamics, to get highest possible armor you would have to think a bit but using any top tier armor combination would still be very good.

Hedgehog
Wouldn't it be easier to keep everything as is, but wearing the full armor set plus shield will grant a little bit extra?

SX 
That is I'm not suggesting full rework of armor values, just to not increase those further as they're already OP but add some dynamics so that different combinations are actually bit more different.
It would be easier, problem I see with that is fact that armors are already way too good for current prices. (Actually it might be easier, not sure as I did not read code or docs...)

**Comment by Klaranth** [comment]
sivarajan 
Please make Hazmat compatible with Space suit.

**Comment by OgelGames** [comment]
The armor bonus was never disabled, so this is a non-issue.
