### ISSUE TITLE
Upgrading biofuel refinery to be more like autocrafter

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#114]
ThinkSome
Biofuel refineries should do catch-up like autocrafters (when you leave an area and later come back)

**Comment by OgelGames** [comment]
Should be fairly easy to implement, I might even try to do it tomorrow...

**Comment by S-S-X** [comment]
Remember that will be really big change for biofuel. I mean REALLY big change.

**Comment by S-S-X** [comment]
Linking few issues that mostly aim to include shortcuts for speeding up game, reducing required space for machines, making mining or processing simply faster as main goal without providing much anything else: #164 #159 #136 #118 #108 #106 #81

**Comment by SwissalpS** [comment]
> Remember that will be really big change for biofuel. I mean REALLY big change.

I agree, even adding the extra fuel step from biofuel mod wouldn't balance that out.
