### ISSUE TITLE
Name on Digtron crate should be preserved after unpacking 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#121]
Thinksome
Digtron crate's description should be preserved after unpacking.

Hedgehog
If only you could name the digtron while in use by adding a name to tthe controller node, and when it is crated, the name is copied to the crate .... much like it is now with the description what is in it

ThinkSome
Stick the name into autocontroller.

SX 
digtron crate losing description is kind of feature... simplest would be to keep description with crate. always. Actually simplest would be to remove input field

Hedgehog
Simplest would be to remove the input field from the crate, and add it to the digtron controller. Then have the crate be named after the digtron it has inside it.

SX
Simplest would be to keep description with crate. always.

Thing is you can only stack ones that have same metadata:
"drawback would be that you could not stack empty crates with different names"

SX 
Storing description with digtron would be kind of better way but it will also be a lot more complex to achieve and probably there's not many devs who actually want to start that while description with crates can be fairly simple thing to do.

**Comment by OgelGames** [comment]
https://github.com/minetest-mods/digtron/pull/97

**Comment by SwissalpS** [comment]
> Storing description with digtron would be kind of better way but it will also be a lot more complex to achieve

especially considering that digtron can have multiple controlers

Edit: a somewhat simpler way to manage the name would be to have a label-module. But that would make design more dificult and wouldn't keep players from adding multiple labels, leaving us with the same problem.
