### ISSUE TITLE
Introduce a miner's hat with torch

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#122]
Introduce a miner's hat with torch recipe. 
Larger light area based on better armor. 
Torch could be technic lv light, rechargeable in battery box. 
Optional : include it in hazmat suit. 

- kennoath & ThinkSome

**Comment by Klaranth** [comment]
@S-S-X 
Would probably suck much less if it was available, would be semi full bright cheat if it was separate group in 6th slot because it would reduce game mechanisms that introduce choices a lot.

Now you have to make decision and there's many possibilities: 
1. place lights while holding pick axe, require carrying lights or picking up after placing. 
2. switch to torch or other light and require switching held item back and forth. 
3. use lava tools but smelt everything you dig. 
4. use beacons to light up large areas but it gets expensive fast and requires tunnel.

**Comment by OgelGames** [comment]
Lava armor should also glow a small amount...

**Comment by Klaranth** [comment]
Will work on the recipe9s) for this.

**Comment by Klaranth** [comment]
Thinksome 
Apparently there already is a mining helmet mod. Blocky Survival admin just told me that it was briefly enabled, but is now disabled due to crashes.
Unknown by Thinksome which mod this was.

**Comment by OgelGames** [comment]
Found it: https://github.com/BlockySurvival/bls_custom/blob/master/mining_helmet.lua

It's based on a different light mod than we have though...

**Comment by Klaranth** [comment]
> Lava armor should also glow a small amount...

UncleSam
Lava armour should also give light like lava multitool.
There's armor bonus for full set, maybe lava armor could have additional bonus there to give light when one is wearing full set.

**Comment by OgelGames** [comment]
I've added support for 3d_armor to the illumination mod (https://github.com/pandorabox-io/illumination/commit/41d398f) as well as some tweaks to light values of lava armor and items (https://github.com/pandorabox-io/pandorabox_custom/commit/b8c991d).

Also, @S-S-X @BuckarooBanzay, do you think we should move the illumination mod to mt-mods now that it's no longer pandorabox specific?

**Comment by BuckarooBanzay** [comment]
> I've added support for 3d_armor to the illumination mod ([pandorabox-io/illumination@41d398f](https://github.com/pandorabox-io/illumination/commit/41d398f)) as well as some tweaks to light values of lava armor and items ([pandorabox-io/pandorabox_custom@b8c991d](https://github.com/pandorabox-io/pandorabox_custom/commit/b8c991d)).

nice :tada: 

> Also, @S-S-X @BuckarooBanzay, do you think we should move the illumination mod to mt-mods now that it's no longer pandorabox specific?

Yes, sounds like a better place :+1: any plans on adding the fork to the contentdb?

**Comment by OgelGames** [comment]
> any plans on adding the fork to the contentdb?

We could do that...

**Comment by BuckarooBanzay** [comment]
> > any plans on adding the fork to the contentdb?
> 
> We could do that...

Added a draft package here: https://content.minetest.net/packages/mt-mods/illumination/ (not released yet)
Current maintainers: SX, OgelGames, BuckarooBanzai (i hope thats alright)

**Comment by S-S-X** [comment]
> > > any plans on adding the fork to the contentdb?
> > 
> > 
> > We could do that...
> 
> Added a draft package here: https://content.minetest.net/packages/mt-mods/illumination/ (not released yet)

Nice, Prob want to use it for a while first before release.

> Current maintainers: SX, OgelGames, BuckarooBanzai (i hope thats alright)

Is that just defaults for org, can always add more if someone wants to join development. That was kind of hint for anyone readimg these, just ask :)

**Comment by Klaranth** [comment]
1hit ; SX 
Idea: create (or find existing if it exists) a mod for a "miner's helmet".  It must be charged electrically (place into battery), and when worn it emits light in front (or above) the player.  The defense value should be minimal.

Related: there's also technic flashlight included in technic mod, not enabled for pandorabox and not sure how good it actually is. You charge it and keep it in tool bar and it consumes batteries slowly while providing some light.

**Comment by OgelGames** [comment]
I always get around to things eventually :)  https://github.com/OgelGames/headlamp
