### ISSUE TITLE
Factional area problem

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#127]
@eshattow
Area Protect with faction area open set enabled, other faction members cannot use jumpdrive; seems like a bug.

@S-S-X  
Factions are not compatible with jumpdrive and not really yet ready for wide use that's not only protection problem factions currently have

**Comment by Klaranth** [comment]
Is this a real bug and should I move it to another repo, or is this as intended, and can be closed?

**Comment by S-S-X** [comment]
Not exactly same thing but for faction area updates there's #31 
And yes this kind of is jumpdrive protection check problem but root of problem is in areas mod protection check and has a lot to do with https://github.com/pandorabox-io/pandorabox.io/issues/654

**Comment by OgelGames** [comment]
Closing in favor of the existing jumpdrive issue.
