### ISSUE TITLE
Golden chest skin feature

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#128]
Knorke :
Can we have an adjustable skin to fit over golden chests? That can show what is inside?

Hedgehog + Gorlock + AceRichman :
Already possible to use colours for the lock, and information can be penciled in. Signs and itemframes are possible for that, too.

**Comment by S-S-X** [comment]
Use LCD screens with mithril chest.

**Comment by OgelGames** [comment]
Closing, basically already resolved, so no need for further discussion. (not as an issue anyway)
