### ISSUE TITLE
Introduce small amount chest for special needs

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#129]
ThinkSome 
Add a chest that is the total opposite to drawers, where you can store a small amount of items (500), but they can all be different kinds. E.g. you could store 500 tools with metadata or 500 water/lava buckets

SX
Size of inventory is probably biggest problem there, it could use custom inventory of course. Storage stack, have to always take last item you put in.

Well, could work about as well with itemsstacks, just like drawer but multiple items behaving last in first out stack
Not sure if it would really be that useful...

**Comment by S-S-X** [comment]
Added mod request label as I don't see any way to do this well with existing mods, I don't think any of existing mods are suitable for this with just some modifications.

**Comment by Klaranth** [comment]
Anyone willing to put their time to this, or is it better to close it?

**Comment by S-S-X** [comment]
I don't think this is really very useful, I mean most players probably wont be interested in collecting crazy amounts of tools.
Think what you already can fit in smallish gold/mithril chest wall. Is there really good use cases for average player? Only thing I can think of is collecting a lot of tools / memory chips / armors but one can already fit a lot of those in chests.

Probably luatools for luac backups and memory chips would be main use case and I think for that use case there's not that many players.

**Comment by Klaranth** [comment]
And, if you really want to add a LOT of stuff in your inventory, use Digtron storage containers and crate the whole. 

Closing this.
