### ISSUE TITLE
'Fair price" channel 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#13]
DarkRoy — 01/23/2021
Shall we open a "fair price" channel for items most sold or requested? I could do prize calculation based on spawn shop prizes (for those people, that to lazy to calculate it.

**Comment by Klaranth** [comment]
DarkRoy — 01/24/2021
I just see a lot asking for price of certain stuffs. So i was wondering to add a discord channel or a trade market place in minetest with calculated fair price. a min and max price. They would have room to decide which price they take.... for those with mining ship could go even lower as that, but yeah... so people get a idea what to do as a "fair price". Not really as a command. If it is possible to set up a command for it, it could help the people to check the fair prize anywhere.

OgelGames (AceRichman) — 01/25/2021
I think it could be a command, in the bot channel... and I was also already thinking of adding something like that...

OgelGames (AceRichman) — 01/25/2021
@DarkRoy the .price command now exists in the #bot channel 
you should even be able to use it from in-game and IRC

**Comment by Klaranth** [comment]
How come I did not know this?    How to use it?

**Comment by BuckarooBanzay** [comment]
> How come I did not know this? How to use it?

ingame with the `#bot` channel, `#minetest-bot` on freenode and the `#bot` channel on discord, you can type `.help` to get some basic directions

**Comment by OgelGames** [comment]
Closing because it already exists
