### ISSUE TITLE
Incompatibility sign on CNC Mk2

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#130]
Ruggila + UncleSam
it would be cool if the CNC machine Mk2 would immediately tell when an input block is incompatible

SX
Simplest it could attempt to disallow putting incompatible stuff into input inventory, displaying some notification for it would be bit harder to do well

Ruggila 
This simple solution sounds good enough...  for the harder solution maybe a red light going on, or the image of the Mk2 CNC in the lower right of the frame could get tinted, or grayed out, or replace with something. Probably in dialog box. 

SX 
With current engine I think visual indicator outside requires either adding entity or adding another node with different textures.

Inside dialog box would be possible. Might not be as nice for planned possible updates trying to improve performance of technic stuff.

**Comment by S-S-X** [comment]
Should probably migrate this to mt-mods/technic

**Comment by Klaranth** [comment]
> Should probably migrate this to mt-mods/technic

Not sure if that would work, without added info from you building the Saw/CNC machine hybrid?

**Comment by Klaranth** [comment]
brlj
Would it be possible to cut terracotta blocks in circular saw?  

Gorlock
Saw makes lots of additional nodes, brlj, and the terracota blocks are so specific, i wonder if it's a good idea

SX 
For new circular saw nodes like Gorlock said those are very heavy addition, single node for circular saw is heavier addition than adding any new random mod from contentdb.
Does not mean that new circular saw stuff cannot be added but it should at least seem that many active players would want to have some specific node added.

**Comment by OgelGames** [comment]
Moved issue to technic mod, closing here.
