### ISSUE TITLE
Add mod : Amorphous metal 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#131]
Ruggila : 
Add mod: 
https://en.wikipedia.org/wiki/Amorphous_metal

SX 
Quickly going through production notes it feels like this could have interesting recipe, some more use cases for freezer?

**Comment by S-S-X** [comment]
This is not useful alone at all, however it was part of longer discussion about #36

**Comment by OgelGames** [comment]
Closing as per SX's comment.
