### ISSUE TITLE
Revamp JD to move JD out of middle of ship

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#135]
Gorlock
JD with dx,dy instead of radius, and even the possibility to have the JD not in the middle.
Huhhila
One variant of non-cube JDs I was thinking of was one that could move /area(s) next to it (but not including itself) as long as their volume was reasonable (possibly with some limit for multi-mapblock cases)

Huhhila, there's actually been area engine included in jumpdrive mod for long time. However it might have some issues or not completely finished, go try and finish it.

**Comment by S-S-X** [comment]
Basic stuff already exists: https://github.com/mt-mods/jumpdrive/blob/master/engines/area.lua
And: https://github.com/mt-mods/jumpdrive/blob/master/engines/area_formspec.lua

No idea what actual state of area engine is but it seems like almost complete with configuration options.
Quickly going through code it seems only `jumpdrive.execute_jump`/`jumpdrive.simulate_jump` would need some refactoring but other than that everything is done already.

@BuckarooBanzay probably would be able to answer that.

For `execute_jump` and `simulate_jump` changes I would propose refactoring those in a way that completely removes dependency to engine node / metadata and let caller handle input ~~meta~~data with possible effects (particles, sounds) and power calculations.
Let `execute_jump` and `simulate_jump` do just basic consistency checks / mapgen checks and start actual moving of given area.
(If really needed possibly add some helper function `jumprive.get_area(pos, radius)` to calculate corners for area based on position and radius)

I mean I think in API there should not be direct dependency with in world nodes or metadata and those should be instead handled by caller on handled through callbacks.

**Comment by BuckarooBanzay** [comment]
> Quickly going through code it seems only jumpdrive.execute_jump/jumpdrive.simulate_jump would need some refactoring but other than that everything is done already.

sounds about right :thinking: i think i already refactored the "main" move-logic to `jumpdrive.move(source_pos1, source_pos2, target_pos1, target_pos2)` so its only the interface stuff thats missing (formspec, place of jd in the moving area)

> For execute_jump and simulate_jump changes I would propose refactoring those in a way that completely removes dependency to engine node / metadata and let caller handle input metadata with possible effects (particles, sounds) and power calculations.

:+1: 

> I mean I think in API there should not be direct dependency with in world nodes or metadata and those should be instead handled by caller on handled through callbacks.

If the performance doesn't suffer, sure

**Comment by S-S-X** [comment]
> If the performance doesn't suffer, sure

It should be about similar but only move some code from jumpdrive.execute_jump/jumpdrive.simulate_jump to engine specific files, causes some code duplication if same effects and sounds are used but in my opinion it is better that way to allow API that is not locked to some defined metadata stuff and allows other mods to create engines that use different effects and possibly get source/target values from some other source like direct chat command / formspec input / internet service / file storage / whatever.

It might even allow tiny performance improvement (not really that significant) by dropping some duplicate calculation / metadata reading.

**Comment by S-S-X** [comment]
See https://github.com/mt-mods/jumpdrive/issues/68
