### ISSUE TITLE
Auto-eject items from autocrafters

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#136]
Gorlock: 
Enhance autocrafters to eject to tubes by themselves without the need for injectors. 
Is there any benefit, performance-wise) to it? 

ThinkSome
Can we have powered technic autocrafters?

Anyway, you can use a lua tube to track what went in, and then trigger timer interrupts until its cleared. You can even query AC's recipe, so you know how many inputs are needed to produce how many outputs.

SX
Query AC's recipe that you just sent for it?

ThinkSome
Query was in the case that it's just acting as a smarter ejector
E.g. techpack has pushers (~equivalent to filters) that only activate when there are items to be pushed out, but it still uses regular checks, right? 

SX 
That's something similar to self contained injector?

ThinkSome:
Similar would be the techpack  (#55) distributor which is basically a horizontal-only sorting tube with 8 stacks of inventory.

SX 
Then it either has to periodically check metadata of other node or hook in between all inventory move callbacks....
Well, for all supported nodes.

ThinkSome 
It could register a callback in the autocrafter API (if such an option existed)

SX
Oh yes if it is just for AC.. I was thinking about chests.. more like filter injectors...

**Comment by OgelGames** [comment]
Main issue with this is autocrafters connect to tubes from all sides, so it would be impossible to know which side to eject items without some way to configure it, which would likely overcomplicate the UI.

**Comment by S-S-X** [comment]
Linking few issues that mostly aim to include shortcuts for speeding up game, reducing required space for machines, making mining or processing simply faster as main goal without providing much anything else: #164 #159 #118 #114 #108 #106 #81

**Comment by Klaranth** [comment]
Thinksome
Has anyone thought about converting pipeworks autocrafters to LV technic?

Hedgehog
That is an odd way of asking, cause the answer could be 'no' , and we can close the issue.

**Comment by SwissalpS** [comment]
as always, if this gains traction again, it can be re-opened. I don't see actual benifit particularly considering the complexity involved.
