### ISSUE TITLE
Airtight checking tool

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#139]
Gorlock 
A tool to check if some cube is airtight.

Use a trace-gas inside ship and see where it leaks ... 

Simulate vacuum expansion in a certain range, and check if the face hit by the tool would be filled with vacuum?

Another action could be to perform the same check assuming the hit node would be removed (can be helpful to know that removing that node would cause a leak).

Can't submerge a ship in water, as water does not behave the same as air/vacuum interaction.  

Hedgehog
Copy and enhance/adjust prospector tool?

**Comment by S-S-X** [comment]
I think vacuum mod and airpump would be best place to implement this to keep it simple and self contained.

**Comment by Klaranth** [comment]
wf13 
add digilines air/vacuum  detector, and make it output a signal until there is no vacuum/air (let it be set to what to detect). 
AceRichman
you could do that with some node detectors or a digibuilder (it can read nodes too), but it might be good to add something more efficient
