### ISSUE TITLE
Planetoid beacon - Earth Gravity 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#14]
DarkRoy — 01/24/2021
a idea for beacon on planetoid. I kind of hate the gravity there... can't we add to beacon a gravity that would change the gravity in range to "earth gravity"?

**Comment by OgelGames** [comment]
https://github.com/OgelGames/beacon/issues/19

**Comment by OgelGames** [comment]
Closing in favor of the issue I linked.
