### ISSUE TITLE
Three way HV Alloy machine ( aka magic wand) 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#140]
Condensed from a discussion in #main with Deeplearning and others. 

Sadly never placed in #ideas, but the whole concept is intriguing. 

Create an alloy machine (HV) that holds three nodes to take properties from:
1 - basic shape and texture  (optional to split this up in two different nodes) 
2 - transparency 
3 - lighting 

After a while out rolls a new custom build node. 

ThinkSome suggested it might be done with parts from TechPack.
More information and discussion needed.

**Comment by OgelGames** [comment]
AFAIK, this is not possible with what minetest can do currently, not without creating a node for every possible combination.

The closest thing would be something using entities, a bit like this mod: https://gitgud.io/deltanedas/covers
