### ISSUE TITLE
Glass support for technic node replacer

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#145]
UncleSam
Glass support for technic node replacer
Technic node replacer dont support volume placement of glass nodes

Huhhila
Current behaviour there is considered a feature...

UncleSam
Is that consideration includes all range of glasses?

**Comment by OgelGames** [comment]
@SwissalpS

**Comment by SwissalpS** [comment]
https://github.com/SwissalpS/replacer/issues/29

**Comment by S-S-X** [comment]
Continue discussion on linked issue.
