### ISSUE TITLE
Batteryboxes vs Powerbanks 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#149]
ThinkSome 
Make batteryboxes keep the energy when dug. Much like powerbanks. 
In terumet, (See also #55 ) which is another machine mod, machines are powered by heat instead of electricity, and you can dig thermoboxes and take their heat with you. And digging machines will preserve the heat in them

OgelGames 
If batteries could be dug without loosing charge, what would be the point of powerbanks?

ThinkSome 
There wouldn't be a point in powerbanks. But I consider powerbanks as the wrong solution to portable power.

**Comment by SwissalpS** [comment]
not an enhancement, not sure though how you are using that label

**Comment by S-S-X** [comment]
> If batteries could be dug without loosing charge, what would be the point of powerbanks?

Powerbanks can work without Technic network connection while battery boxes cannot, witching station and cables would be required to use charge in battery box anyway.
Battery boxes would not be as good portable power stations, stacking battery boxes in inventory would be affected.

Would not affect power banks that much but still I don't really see keeping charge very useful, could be useful in some corner cases but could also make some things more complicated.

**Comment by OgelGames** [comment]
I should point out, the technic wrench can pickup batteries keeping their charge, and the wrench should be craftable in the near future... ;)
