### ISSUE TITLE
Custom uploadable skyboxes 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#15]
sunks — 01/26/2021
custom uploadable skyboxes for players in some x y z range?
censored nudity/drug propagation condition ofc. for upload

BuckarooBanzai — 01/26/2021
have you tried using a client-side texture pack, i think that should even work... :Thinkeyes:
(the lazy option, i know :slight_smile:)

sunks — 01/26/2021
won't pandora try to erase it?
I wanna try it now tho
on singleplayer let's see  how nice it works

BuckarooBanzai — 01/26/2021
basically: if you have your own texture pack, and the images have the same name as here for example: https://github.com/pandorabox-io/planet_mars/tree/master/textures the client should use those instead
GitHub
pandorabox-io/planet_mars
planet mars for minetest. Contribute to pandorabox-io/planet_mars development by creating an account on GitHub.

<details><summary></summary>
OgelGames (AceRichman) — 01/26/2021
hmm... i wonder if a hdr skybox is possible... :thinking:
i guess the only limit is what the max resolution MT can handle is...

白狐 — 01/27/2021
i don't think pandorabox would erase client side textures, more just download them and end up not using the downloaded ones

SX — 01/27/2021
I tried some approx 4000 x 4000 photos for those technic machines, server start took some more time but seemed to work without problems

OgelGames (AceRichman) — 01/27/2021
i used six 4k images for the hdr skybox test, and it hard crashed when i put them in the mod, but worked fine when i used them as a client texture pack

SX — 01/27/2021
and 4k is just about half of that.. :thinking:

OgelGames (AceRichman) — 01/27/2021
4k as in 4096 * 4096

SX — 01/27/2021
also had multiple textures when I tried, I think 5 different
I did also ran all through optipng with all cleanup switches, could that make difference?

OgelGames (AceRichman) — 01/27/2021
maybe, i didnt try that...

OgelGames (AceRichman) — 01/27/2021
no, it doesn't help, MT just can't handle the file size (77.6 MB total)
this is what is in the log:

> INFO[Main]: Client: Sending media request list to server (6 files. packet size)
INFO[Main]: Client::ReceiveAll(): Packet processing budget exceeded.
INFO[Server]: Sending 6 files to [id=2]
VERBOSE[Server]: TOSERVER_REQUEST_MEDIA: requested file nx.png
VERBOSE[Server]: TOSERVER_REQUEST_MEDIA: requested file ny.png
VERBOSE[Server]: TOSERVER_REQUEST_MEDIA: requested file nz.png
VERBOSE[Server]: TOSERVER_REQUEST_MEDIA: requested file px.png
VERBOSE[Server]: TOSERVER_REQUEST_MEDIA: requested file py.png
VERBOSE[Server]: TOSERVER_REQUEST_MEDIA: requested file pz.png
VERBOSE[Server]: Server::sendRequestedMedia(): Sending files to client
VERBOSE[Server]: Server::sendRequestedMedia(): bunch 0/7 files=1 size=15472568
VERBOSE[Server]: Server::sendRequestedMedia(): bunch 1/7 files=1 size=27554541
WARNING[ConnectionSend]: con(1628/1) Packet quota used up for peer_id=2, was 1024 pkts
VERBOSE[ConnectionSend]: con(1628/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=0.1): from_peer_id=1, channel=2, seqnum=386
...
VERBOSE[ConnectionSend]: con(1628/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=0.1): from_peer_id=1, channel=2, seqnum=30170
ERROR[ConnectionSend]: In thread 78c:
ERROR[ConnectionSend]: connection.cpp:3f9: con::UDPPeer::processReliableSendCommand: An engine assumption 'c.data.getSize() < 0x8000*512' failed.
</details>

**Comment by OgelGames** [comment]
Client texture packs can be used for custom skyboxes, probably don't need anything more than that...

**Comment by Klaranth** [comment]
Naso 
Do we have skybox texture support for earth as we do for space? I'd love to be able to slap in an image and do away with gradients :p
wsor 
no, you can either have textures or set sky colors, not both

**Comment by SwissalpS** [comment]
Sunkenhero may have been asking about something not possible with client texture packs. Showing different sky above moon station than above a moon base further e.g. east.

**Comment by Klaranth** [comment]
Marsufoman
Can we please have a more interesting skybox
frog
Thats very possible actually, just needs 1 particle spawner
frog 
also this mod looks pretty good https://github.com/minetest-mods/skybox
