### ISSUE TITLE
Digtron-like functionality for technic

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#152]
ThinkSome 
I wonder if technic could get digtron-like functionality. So instead of a quarry node that makes stuff disappear far away, you can build electric powered digging machines. Although I still think that technic quarries are made completely obsolete by digtrons.

Test_User
Quarries are still very useful, you can shove a ton on a jumpdrive, automate it to jump around and restart the quarries. Hard to do that with a digtron.

Hedgehog 
There is a limit to the amount of quarries that can work right without penalties. Putting 80 quarries on an R15 doesn't work so good.

**Comment by OgelGames** [comment]
Digtrons can already be powered by batteries or a technic network.

**Comment by S-S-X** [comment]
Digtrons can also be completely automated for single step move, dig or build to do for example fully automated farming. Only multi step working cannot be completely automated, only partially.
