### ISSUE TITLE
Digtron builder checkbox to not stop when empty

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#159]
ThinkSome 
Digtron builder has no checkbox to not stop the digtron when running out of materials?

Hedgehog
if it has nothing to build why do you want to make it continue building ?

ywang
Because it breaks his workflow if the digtron stops running? 

Thinksome 
Hedgehog the idea is for digtrons where you are only interested in ore. So you build a digger - control - combined storage - cobble builder and send it down. When it stops, storage has only not-cobble.

SX (TLDR : Tune your trons better.) 
you can simply use fewer builders and get pretty good results, of course this needs different setups for earth/moon/asteroids because of varying ores to stone ratio. However also constant number of builders with such skip-if-no-material option would be inefficient when ratio changes.

**Comment by S-S-X** [comment]
Linking few issues that mostly aim to include shortcuts for speeding up game, reducing required space for machines, making mining or processing simply faster as main goal without providing much anything else: #164 #136 #118 #114 #108 #106 #81

**Comment by S-S-X** [comment]
Probably wont happen, there's seems to be no real use for this feature and in original request it is also only request to have a way to throw away unwanted dug items.
Even if such feature would be added builder configuration for sure is not correct way to do it.

Open issue to digtron repository if still interested.
