### ISSUE TITLE
Cave detector mod

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#16]
Houlley — 02/03/2021
i think a cool and random idea for a mod is a cave detector..the device detects if there is a cave nearby and has a range of several map blocks
so if you reach a dead end and explored one cave, the cave detector will help you find the closest adjacent cave
maybe the feature could be added into the current technic prospector

wsor — 02/03/2021
What determines a cave? The nearest air pocket?

SX — 02/03/2021
this has one problem if range would be bit more than very limited: areas that are not yet generated cannot be searched

wsor — 02/03/2021
Or loaded
Wait, maybe not

SX — 02/03/2021
yea voxelmanip would probably anyway be best option for searching large area if unsure if it is loaded or not

OgelGames (AceRichman) — 02/04/2021
such a thing kind of already exists, but cannot be used currently: minimap radar, which shows places where there are pockets of air

Houlley — 02/04/2021
Wait so is this disabled in game? And is there reason if it is?

OgelGames (AceRichman) — 02/04/2021
yes, i think it was just deemed too overpowered for MTG, that's why the mapping kit only enables the surface mode of the minimap
it can be enabled using another mod though

BuckarooBanzai — 02/04/2021
i don't see a problem with enabling that, the radar can't display depth really good anyway :stuck_out_tongue:

OgelGames (AceRichman) — 02/04/2021
so... i might have got a bit carried away and made a mod for that... but i think others might also want a simple mod to enable the radar :) https://github.com/OgelGames/minimap_radar
GitHub

OgelGames/minimap_radar
Minetest mod that adds an item to enable the minimap radar - OgelGames/minimap_radar

BuckarooBanzai — 02/04/2021
wow, that looks nice :astonished:  (i took the liberty: https://github.com/pandorabox-io/pandorabox-mods/pull/1394)

**Comment by OgelGames** [comment]
Closing this, I don't see any reason to keep this open, the minimap's radar mode is effective enough.
