### ISSUE TITLE
Customizable JD placer

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#161]
<UncleSam> 
can a tool like protector block placer be possible for JDs? A jd placer with customizable range.

Huhhila
Quite many ships need varying JD radius, which could get quite complicated with such? And such would also lead to more demand for area creation helpers...

**Comment by OgelGames** [comment]
Yeah, but nah... It's not *that* time consuming to place jumpdrives, especially when you still have to connect them to a fleet controller 😉

**Comment by S-S-X** [comment]
> Yeah, but nah... It's not _that_ time consuming to place jumpdrives, especially when you still have to connect them to a fleet controller 😉

Agree with that. Also I think actual use for such tool would be too limited and kind of redundant or it would get way too complicated.
If such tool would be added it probably would anyway be better to have generic tool with player configurable node, distance and such.

For something supposed to be survival setting generic tool like that in my opinion would however be too much as combined tools would already be near WE level.

I'd say not needed and should not be added for such simple task.
