### ISSUE TITLE
Change mosaic usage

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#162]
Gorlock
We used to have automated teleporting IIRC (just walking on mosaic). It was changed to manual action. I wonder if there is rationale behind this, and if triggered teleport would be nice to have back (could be in the form of a plate too, activating mosaic)
OTOH I understand that teleporting without user consent might raise abuse issues.

**Comment by S-S-X** [comment]
Reason why automatic teleport was removed were problems that caused automatic teleporting back and forth and added server workload that was seen unnecessary.

There was attempts to fix first issue by providing separate departure and arrival telemosaics, this however limits use and many players did not understand why this was needed or better way than single telemosaic both ends. Multiple telemosaics were of course also more expensive and consumed more space.

This did not work well so automatic teleport was removed and changed to require clicking telemosaics, this reduced server load as there's no need to track player locations to see if any of players is standing on top of telemosaic. Also it immediately fixed getting trapped in wormhole going back and forth between 2 telemosaics.

**Comment by OgelGames** [comment]
Closing as per SX's comment.

**Comment by Klaranth** [comment]
Huhhila
related to #162, have telemosaic check size of the passenger (instead of stuffing their head in default:stone); add a player:get_properties().collisionbox intersection check instead of node_above/node_top in https://github.com/mt-mods/telemosaic/blob/5edebccdb0cb8bec4df2025203f4015726e197d3/functions.lua#L82,L332 - that could also support chicken-mode players as well as teleportation of mounted entities. Might also lead to more acceptable reimplementation of 0-click telemosaics.

telemosaic/functions.lua at 5edebccdb0cb8bec4df2025203f4015726e197d...
A Minetest mod for user-generated teleportation pads. - telemosaic/functions.lua at 5edebccdb0cb8bec4df2025203f4015726e197d3 · mt-mods/telemosaic

**Comment by SwissalpS** [comment]
(would have been better to open a new topic for this)

**Comment by OgelGames** [comment]
https://github.com/mt-mods/telemosaic/issues/12
