### ISSUE TITLE
Extractors / Grinders identical look needs changing

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#167]
Gorlock
MV extractors shouldn't look as grinders. Confusing

Shadow 
This has entered discussion a few times. It could be changed if someone wants to do the work of making art

**Comment by S-S-X** [comment]
This would most probably be better in https://github.com/mt-mods/technic/issues list.
Basically just requires someone to draw some new nice textures or modify old ones a bit preferably following current style of machines.

**Comment by OgelGames** [comment]
I think there are some other machines that also share textures IIRC.

**Comment by Klaranth** [comment]
Wouldnt it be easier to just change the colours on one?

**Comment by OgelGames** [comment]
Moved to technic mod, closing here.
