### ISSUE TITLE
Adding World Calendar - Server issue 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#169]
Huhhila
some way for test server to report which backup of the world it is running

SX
Add in world calendar to prod server somewhere where there's already anchor keeping things running
Way to do it in game using currently available stuff, lua controller, nic, some display to show current time. Only update time if thing is running on main server.
So then on test server you'll have last updated timestamp from main server which is backup timestamp.

**Comment by SwissalpS** [comment]
So far, I've left signs and similar, if they show up on testserver, it's time to test that system.
Maybe a NIC could request a cgi on pandorabox.io that responds depending on ip of caller.
So far you can do that with your own server, but I see how having that run on pandorabox.io would be useful as a service.

**Comment by S-S-X** [comment]
NIC can be used to query IP address and that IP address can be used to query DNS to get host name.

**Comment by SwissalpS** [comment]
true, a code snippet in the luac-code-collection-repo should suffice.

**Comment by S-S-X** [comment]
Someone can just do this if interested, no need to keep this open here.
Only very few users will use this and probably even those users wont use it very often.
Anyone can make this happen, no special privileges or any kind of admin access needed.

Open new issues as bug reports to mod repositories if something does not work while using Digistuff NIC + Lua controller + digiline screen (unlesss it is your own lua controller code).
