### ISSUE TITLE
Automating XP gain

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#17]
sunks — 02/04/2021
player potato has suggestion for smelting and cooking to give XP's

OgelGames (AceRichman) — 02/04/2021
builds a huge array of furnaces and cobble generators
but seriously, making it possible to automate XP gain is something to be avoided...

**Comment by S-S-X** [comment]
Most of something have been done to prevent automating XP gain, some examples:
https://github.com/pandorabox-io/pandorabox.io/issues/177
https://github.com/pandorabox-io/pandorabox.io/issues/226
https://github.com/pandorabox-io/pandorabox.io/issues/228
https://github.com/pandorabox-io/pandorabox.io/issues/248
https://github.com/pandorabox-io/pandorabox.io/issues/611

This idea has a lot of problems to solve, test and think through before it could be possible in a fair and balanced way.

**Comment by SwissalpS** [comment]
please close, waste of my github time :p

**Comment by OgelGames** [comment]
Closing as per SX's comment.
