### ISSUE TITLE
Adjust shout / whisper / etc

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#171]
Gorlock
We don't have a shout command(s) by the way, do we? Same as whisper but on bigger range(s)?
SX 
Whisper has 200 max range, default is lot shorter

**Comment by S-S-X** [comment]
Could still ask if 200 is good enough, many players do not know about this because they've already played before and think that they don't need starter tutorial

**Comment by Omikhleia** [comment]
Some ideas, about different range commands (from whisper to yell, or whatever). I am on Mars (or Moon, whatever, that's an example), and "shout": hello martians. This could have a range large enough in X/Z (not necessarily full) but reach martian levels only.

**Comment by S-S-X** [comment]
> This could have a range large enough in X/Z (not necessarily full) but reach martian levels only.

There if doing that then probably best would be to cover whole layer and only check elevation (it will be extremely long range already so I don't really see any point in limiting horizontally).

One way to do it would be to allow adding special chat channels (with beerchat extension) and automatically join players when entering some specific elevation and part channel when they leave area.

Messages would appear like channel messages, channel name would be "earth", "moon", "space", "mars" for example and sending messages to said channel would be done just like how any other channels are used.

Under the hood it would allow creating physically localized chat channels for some selected area defined similar way how area protections are defined and wont have to actually check player locations every time when message is sent.

**Comment by SwissalpS** [comment]
I like the idea of channel per layer as long as I have a way to opt-out ;)

**Comment by OgelGames** [comment]
Whisper range can already be extended by specifying it, another command isn't needed.
