### ISSUE TITLE
Starter channel for newbs help

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#177]
SX ; Hedgehog ; Vamp

Set up system for new players to be granted chat privileges after player has visited and open few tutorial books, include test at the end to be granted privs. (Beerchat extension) 

Add a little walk from Tutorials, answer questions correctly to get to missions button for privs.  Give wrong answers, different door opens that leads to lava lake, where they have to /spawn out. 

Can this be done with shout priv as well? Until players pass the test they are mum ...

Alternative: 
For chatting, introduce new channel, for players to stay in to learn about how to get to #main. Keeps noob advice in one channel and out of #main. And players willing to help newbs can join the newb channel.

**Comment by S-S-X** [comment]
Won't be just in game task and requires changes to current XP privilege system.
Probably requires changes to server customization mod, beerchat and some in game missions.

**Comment by S-S-X** [comment]
Highly related: #173

**Comment by OgelGames** [comment]
I don't think it's a good idea to prevent new players from using chat, otherwise there is no way for them to seek help.

**Comment by S-S-X** [comment]
> I don't think it's a good idea to prevent new players from using chat, otherwise there is no way for them to seek help.

That's not what it is about, better read full discussion as it seems description here is not exactly accurate.

**Comment by S-S-X** [comment]
Actually it might be better to close this and open new issue with key points most agreed with, description here does not seem to reflect that very well...
