### ISSUE TITLE
Voting systems

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#178]
Huhhila ; SX ; Thinksome ; Hedgehog ; Ywang 

Using different voting systems on contests, etc. 

Draft votes for expo: 1st, 1st, 3rd, 3rd, 5th, 5th, 7th, 8th, 9th, ... any voting systems allow voting like that?
Simple to implement but far too complex for users.
Touch screen interface could at least have something similar to skill point selector interfaces in some games. Just points you can spend on entries.

Other voting systems:
Give 8/5/3/1 points
Have UIs that allows only sorting a list
Have 20 points you can distribute any way you want
Use Borda count method (or similar)
https://www.debian.org/vote/ 

On Debian :
Biggest problem would be text only interface (chat voting), graphical UI would work a lot better but would still require a lot of effort for voting.

Regarding the earlier voting secrecy vote... the approach used by debian for "gr_initsystems" vote sounds quite good: Public after voting period is over, only who-has-voted visible during voting period.

Testing voting systems UI:
We could build few simple touch screen setups, then vote for best UI :p
All without any backend, just user interface to see what works for users.

**Comment by Klaranth** [comment]
Debian voting does actually use text-only interface, but I'd consider their email approach more user friendly than being limited by beerchat interface. Checkboxes can be compressed to one-liners, as is done in their tallies: https://www.debian.org/vote/2019/vote_002_tally.txt
(well not really checkboxes but the [ ] <--put ranking number here forms...)

**Comment by OgelGames** [comment]
Closing in favor of #195
