### ISSUE TITLE
Showing other servers ingame

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#179]
Huhhila ; Gorlock 

Utilize a NIC to make other server player stalking UI to show https://www.minetest.net/servers/ ingame. Luac would likely barf at 1291 players.

Doesn't NIC have some limitations (no JSON, no POST)?
It got JSON capability recently, but this project could test that.

**Comment by S-S-X** [comment]
Selected JSON values also can be easily parsed without any special JSON support.
Similar way web site content can be very easily parsed (for server list based on table cell class for example), it does require web site returning similar structure every time however.

I've used fast string parsing to grab metadata values using lua tube and can say it is very simple thing to do if you only want some selected well known keys. That can be used to grab server name and players easily.

Response length limit might be problem but unless there's web site or API that provides shorter response then nothing can be done for that other than allowing longer response texts.

**Comment by S-S-X** [comment]
Someone can just do this if interested, no need to keep this open here.

Open new issues as bug reports to mod repositories if something does not work while using Digistuff NIC + Lua controller + digiline screen (unlesss it is your own lua controller code).
