### ISSUE TITLE
Craftable lava mod request

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#181]
Mod request : Craftable lava. ( Cooking stone will give hot stone > 8 hot stone + bucket gives 1 lava in a bucket. Also hot stone is a light source. And can be used to build with.
Terumet has similar, but that won't work with technic.

**Comment by S-S-X** [comment]
Cooking obsidian + bucket in alloy furnace should give you lava. It wont allow generating infinite amounts but practically speaking world contains infinite amounts of lava already.

**Comment by OgelGames** [comment]
It is actually already possible to create infinite lava, it's just very slow; collecting obsidian dropped from obsidian flans, and then turning that into lava using the alloy furnace.

It would be nice though to make it possible to melt stone (or compressed cobble) into lava, even if the cooking time was long.

**Comment by OgelGames** [comment]
```
<\Test_User@IRC> specing: lava orbs can be turned to lava, last I checked
* FeXoR finds that apropriate: One barely useless thing convertable to another one :p
```
Hmm... 🤔

**Comment by S-S-X** [comment]
> ```
> <\Test_User@IRC> specing: lava orbs can be turned to lava, last I checked
> * FeXoR finds that apropriate: One barely useless thing convertable to another one :p
> ```
> 
> Hmm... lava orb + bucket = lava bucket? (or maybe multiple buckets) 🤔

Lava ingot + bucket would cut needed orbs to half but would also add mese to recipe, too expensive?
Possibly orb + 2 buckets to 2 lava buckets?
Lava ingot + 2 buckets alloy recipe to 2 lava buckets?

**Comment by Klaranth** [comment]
Yes - 9
 No  - 4

<VoteBot@bot> Votes for "Introduce craftable lava (#181)":
 OgelGames — Yes
 Klaranth — Yes
 DakotaVeronica — Yes
 marghl — Yes
 Huhhila — No
 xman — No
 PhrogMan — Yes
 SX — No
 SamWorld — Yes
 Lejo — No
 SimonSays — Yes
 Vamp — Yes
 Eula — Yes

**Comment by OgelGames** [comment]
Seeing as this is decided on now, I propose adding two recipes:
- Lava orb + bucket in craft grid - The ease of crafting balances the expensive recipe.
- Compressed cobble + bucket in alloy furnace - The additional step and long cooking time balances the cheap recipe.

Still not quite sure how long the cooking time should be, or if the recipe should cost multiple compressed cobble...

**Comment by S-S-X** [comment]
> Seeing as this is decided on now, I propose adding two recipes:
> 
> * Lava orb + bucket in craft grid - The ease of crafting balances the expensive recipe.
> * Compressed cobble + bucket in alloy furnace - The additional step and long cooking time balances the cheap recipe.
> 
> Still not quite sure how long the cooking time should be, or if the recipe should cost multiple compressed cobble...

I think Lava orb + bucket in craft grid is not really balanced when comparing with compressed cobble recipe unless alloying is ridiculously slow.
I believe recipe using lava orb could very well allow lava orb + technic canister for 8 sources and would probably still be a lot worse option.

**Comment by OgelGames** [comment]
> I believe recipe using lava orb could very well allow lava orb + technic canister for 8 sources and would probably still be a lot worse option.

Is it even possible to use technic cans in recipes? Last time I checked it didn't work... unless I didn't do it right... 🤔

**Comment by S-S-X** [comment]
> > I believe recipe using lava orb could very well allow lava orb + technic canister for 8 sources and would probably still be a lot worse option.
> 
> Is it even possible to use technic cans in recipes? Last time I checked it didn't work... unless I didn't do it right... 🤔

Tools can be used (including technic cans) in recipes, also you can set metadata for recipe output (see shared anvil).

**Comment by S-S-X** [comment]
Including simple example:
```lua
local output = ItemStack("technic:lava_can")
minetest.register_craft({
	type = "shapeless",
	recipe = { "technic:lava_can", "default:cobble" },
	output = output:get_definition().on_refill(output):to_string(),
})
```
![screenshot_20211103_154108](https://user-images.githubusercontent.com/50966843/140071259-ce34c773-1a7f-4941-b4ff-092f41a0010f.png)

**Comment by OgelGames** [comment]
Ah right, they can be used for output but not input (previous use case was filling can by combining with buckets).

How about this:
```lua
local output = ItemStack("technic:lava_can")

minetest.register_craft({
	type = "shapeless",
	recipe = {"technic:lava_can", "mobs:lava_orb"},
	output = output:get_definition().on_refill(output):to_string(),
})

technic.register_alloy_recipe({
	input = {"moreblocks:cobble_compressed 10", "bucket:bucket_empty"},
	output = "bucket:bucket_lava",
	time = 20
})
```

**Comment by BuckarooBanzay** [comment]
> (I would also like to get @BuckarooBanzay's thoughts on this)

Sounds good, this translates to 20 seconds ingame alloying time, right? If so: :+1:

**Comment by OgelGames** [comment]
> this translates to 20 seconds ingame alloying time, right?

Yep 👍
