### ISSUE TITLE
Mix of JD and digtron: have a house packed in a crate

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#187]
Gorlock ; SX 

Mix of JD and digtron: have a house packed in a crate

Built and used before: basically moving digtron with jumpdrive and having simple luac to move jumpdrive to correct position where digtron stops, possibly with automated system to replenish building materials and fuel.

I think those were primarily used for digging but also for some simple building, if I remember correctly things like that were possibly used when HiFi city was built.
But I'd have few digtrons that build decorated house walls with windows and stuff like that so automated house building with those would just require jumpdrive engine and some luac code to run things.

**Comment by S-S-X** [comment]
These can be already found from game and multiple, just have to find those... I don't think we need issue here if someone wants to build setup that can be easily cloned.

As tutorial this is way too narrow and specific, I think everything needed is already explained in existing tutorials, it is just about connecting things in certain order to get specific outcome and there's countless possibilities.
