### ISSUE TITLE
Adjusting Discord's slowmode 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#188]
SX ; UncleSam ; BuckarooBanzai

Adjusting Discord's slowmode 

There was discussion about it before too. What I'm suggesting would be remove slow mode and require authentication with pandorabot to talk on main channel from Discord or IRC. There's some downsides but benefit would be that in game everyone could see actual player name instead of some different nick that player is using on external chat, it would also allow easier private messages from game to Discord and IRC.
And yes, complete integration is impossible. players would still appear with their external chat platform nick on DIscord and IRC. On discord forcing nick change might be possible, not on IRC. Even if possible not sure if it would be that nice thing to do....

Make slowdown 15sec instead of 60

The "contributor" role does not have a slow-mode (a contributor is someone that helped improve pandorabox somehow, let me know if someone doesn't have the role and feels like he/she should have it...)

**Comment by OgelGames** [comment]
Related:
https://github.com/pandorabox-io/pandorabox.io/issues/678
https://github.com/minetest-beerchat/beerchat_proxy/issues/47

**Comment by OgelGames** [comment]
@BuckarooBanzay any thoughts on this? Otherwise this can probably be closed, in favor of the other issues.

**Comment by BuckarooBanzay** [comment]
> Make slowdown 15sec instead of 60

Done :+1: i reduced it to 5 seconds until someone decides to spam the `#main` channel again :/
Not sure about this but i think `staff` can modify the slowdown too, maybe give the privilege to `contributors` too?

> @BuckarooBanzay any thoughts on this? Otherwise this can probably be closed, in favor of the other issues.

Yes please :smile:

**Comment by OgelGames** [comment]
> Not sure about this but i think `staff` can modify the slowdown too

Yep, we can 👍

> maybe give the privilege to `contributors` too?

IDK, it's also the privilege for creating and deleting channels, so maybe not...
