### ISSUE TITLE
Increasing Digtron node limits

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#192]
UncleSam ; Hedgehog ; Thinksome ; SX 

Can digtron nodes limit be increased to twice the amount for experienced players. Basing it on their XP, suggesting 750K XP for double the amount.

Twice the original amount at 750K, three times the original amount at 1.5 million XP ? And so on?

Alternatively, from 750K XP increase limit by 1 head every 10K XP above 750K. 

One downsize : 
Lower level players can no longer use all digtron crates, from higher level players. So, if they want to help in a project, .... there is no trade or exchange happen.

There's limit for reason and that reason is lag. Moving very large digtron causes many problems.

Can the digtron controller check for lag and refuse to work over standard limit at lag > 5?
No, controller cannot check lag and work based on that because of what under the hood actually causes problem.

There's at least one way that could be used to allow bit larger trons (not much but still way larger area) and that is to force minimum interval based on digtron component count. Basically larger it is slower it gets.

It is time used per cycle that matters, basically digtron causes server to freeze for some time and larger it gets longer it takes. That's why interval scaling wont allow that much but just a bit.
Proper way to do it (allow unlimited scaling) would be to rewrite digtron code almost completely so that it could distribute work over multiple server steps. Not sure if current rewrite project has this goal or not, probably not... Doing that also has downsides, it is not that simple.
Middle way would be to optimize digtron code as much as possible and reduce server load through that, I think there would be many things that would allow significant performance increase through optimizing code. However I think nobody wants to actually do that with current digtron code.

**Comment by S-S-X** [comment]
Older but related discussion: https://github.com/pandorabox-io/pandorabox.io/issues/504

**Comment by OgelGames** [comment]
The limit is there for a reason, and I think it's at the correct value. If the digtron mod ever gets updated to be more efficient, they sure the limit could be increased, but until then I don't this anything needs changing. Closing this.
