### ISSUE TITLE
Stasis field item which stops user 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#200]
Huhhila ; SX 
    Stasis field item which stops user still for a short time, protected from elements... and resets things like glider to their initial state. Should need relatively high charge for activation and lower discharge rate while in use.

If it would freeze user completely disallowing all possible actions that affect player or world then probably not too powerful. That would include crafting, eating, swapping armor, teleport and so on. But would it then have any real use other than game paused for single player in multiplayer game...
Well, maybe one could use enough those to make player more efficient world anchor for afk gaming style running machines and so on...
Huhhila, what would be use case you were thinking about? In what situation player would possibly want to use such item? That probably affects a lot how exactly it should work like what to allow and what to prevent from happening.

Was mainly thinking about bug-pause/doorbell-pause. And I find needing to have a roof on top of /home location on earth rather silly... just to prevent glidering all the way up to moon or beyond when buggy times eventually happen.

**Comment by S-S-X** [comment]
I think this is somewhat related: #6

**Comment by Klaranth** [comment]
FeXoR
Always make the charge state of an item visible e.g. by showing a black bar instead of transparance as background
(To comunicate more clearly to the player that this item is empty and needs charging)
SX 
Maybe also some simple nice generic sounds if/when trying to use power tool without enough charge.
