### ISSUE TITLE
Fees to admin for wire Transfer  

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#203]
chuche952 ; Huhhila

Make Wire Transfer charge 1% of money for service.

Not particularly fan of mirroring non-fun elements of RL into a game :) Unless the game's name is europarlament-simulator... https://www.europarl.europa.eu/doceo/document/E-9-2020-002290_EN.html 
Otherwise next we might be introducing PHBs, marketing and legal departments as well as hour reporting (at every minetest hour?)

**Comment by S-S-X** [comment]
Removed my name from list because nothing I said was quoted in description.

**Comment by S-S-X** [comment]
Opinion about idea itself, I think it is not good.
Making it useful addition would require reworking whole money circulation system and possibly some other elements that would somehow make expensive payment options better or required in some situations.

Implementing just wire transfer fees, be it fixed or percentage, is probably bad idea. I also think that complete overhaul for money would be bad idea and most probably would not support it.

However I wont be against it if someone is able to pull it off creating new working and balanced system that is also fun, I just think that doing this properly is probably too much work and too hard.

**Comment by S-S-X** [comment]
Changed labels because this cannot be done as in-game task.

**Comment by OgelGames** [comment]
Yeah, nah... I agree with Huhhila:

> Not particularly fan of mirroring non-fun elements of RL into a game

**Comment by S-S-X** [comment]
Closing this: no progress or chat activity and almost everyone seems to disagree with idea in its current form.
