### ISSUE TITLE
Disallow eating dung and mulch by player

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#204]
chuche952 
Disallow eating dung and mulch by player.

**Comment by OgelGames** [comment]
I think that's probably supposed to be "allow", dung doesn't exist, and mulch is not edible...

Either way, a strange idea :P

**Comment by S-S-X** [comment]
Bit too unclear and probably either wont be changed or wont need anything depending if it was about allowing or disallowing...
Link to #124 and closing this.
