### ISSUE TITLE
Moving travelnet buttons down to go to the top 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#206]
Vamp
Being able to move a travelnet button down to get to the top of the list, so that you dont have to go through the whole list to the top when you want your last placed box to get there moving it up instead
Which would also be good with the inventory list

**Comment by S-S-X** [comment]
> Which would also be good with the inventory list

Does that mean crafting guide paging? So that last page jumps back to first page if you use button that normally advances to next page?
If that then I think there's also dedicated button to do that, duplicating functionality to next/previous buttons might not be good idea and would require refactoring/redesigning navigation system.

**Comment by OgelGames** [comment]
I think travelnet should replicate the crafting guide; add "move to top" and "move to bottom" buttons.

**Comment by S-S-X** [comment]
> I think travelnet should replicate the crafting guide; add "move to top" and "move to bottom" buttons.

I think cycling around with existing up/down buttons would probably be better to keep number of ui elements limited, top/bottom buttons wont add that much functionality. Asked for opinions, did not get many answers but here's chat log anyway:

> **SX:** Vamp, there was suggestion about adding similar first/last buttons to travelnet configuration interface. Not sure which would be better, first/last or cycling around with up/down buttons. Opinions for that?
> **SwissalpS:** there is already up/down. what would first/last be good for? Doesn't seem to be something I do a lot: re-ordering stations
> **SX:** Using existing buttons saves space but you cannot send to top/bottom from middle, additional first/last uses more space in UI but allows setting station directly as first or last even from middle..
> **SX:** (I think that also answers what additional functionality additional first/last buttons would provide)
> **SX:** Cycling around would be kind of "safe" addition: no formspec changes so different bscreen sizes wont break and it would still provide faster way to send added travelnet to top of list.
> **SwissalpS:** on smaller screens the current buttons are already obscurring readability
> **Vamp:** so if you mean using down button when you are at or nearer the bottom of the list than the top, yeah, i think it would be good enough
source: https://discord.com/channels/513329453741637637/668090931861258250/889582662984040458

I've not tried devices with smaller screen myself but it seems like SwissalpS has and could be good to update formspec layout a bit while adding functionality for up/down buttons (or while adding new buttons if it seems fine but I think it is unnecessary for very little value).

**Comment by S-S-X** [comment]
> Vamp: be able to change a travelnet box station's name without having to remove it and placing it back again

If formspec will get update it would be good to consider this while doing it. A lot of buttons and other stuff however is not good thing on travelnet main form and therefore I'd suggest swapping _"Remove station"_ button with _"Edit station"_ button and open another formspec when that button is pressed:
Text fields: _"Station name"_, _"Network"_, possibly also _"Owner"_. Here it would actually be good to reuse original configuration form but fields prefilled with current configuration values, basically allow full reconfiguration without remove+place again.

**Comment by SwissalpS** [comment]
[I've worked on a proposal for changing station name, network and owner of travelnets and station name of elevators on this branch.](https://github.com/mt-mods/travelnet/tree/editableStation)
Please test, review and suggest improvements.

**Comment by Klaranth** [comment]
@OgelGames   Based on : 

(that #212 closing at least for travelnet; consider opening another issue for other non-travelnet and check whether https://github.com/mt-mods/travelnet/pull/24 can also be considered to close #206)
GitHub
Editable station by BuckarooBanzay · Pull Request #24 · mt-mods/tra...
See #23
by @SwissalpS (i took the liberty of creating a PR ;)

can this be closed?

**Comment by SwissalpS** [comment]
seems #206 is a duplicate, so yeah close this

**Comment by OgelGames** [comment]
This still hasn't been done yet, you get an error message if you try to move stations beyond the ends of the list.

**Comment by OgelGames** [comment]
Opened issue in travelnet repo, closing this.
