### ISSUE TITLE
Identical recipes 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#209]
Huhhila
xpanes:trapdoor_steel_bar and glass_stained:pane_bar_single have identical recipe, people have been mentioning that for quite a while now

**Comment by Klaranth** [comment]
OgelGames
https://github.com/pandorabox-io/pandorabox.io/issues/421#issuecomment-609597201

**Comment by OgelGames** [comment]
Will be fixed by https://github.com/v-rob/glass_stained/pull/1, closing this issue as it's a duplicate of pandorabox-io/pandorabox.io#421 (which is where bug issues should be submitted anyway)
