### ISSUE TITLE
Show of country at player's name

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#21]
SX:
Would be interesting to see list of countries where players are coming to pandorabox, pairs of country + player count maybe some top 3-6 listed at wiki front page

Hedgehog:
Would it be possible to add flags or [NL] / [DE] etc in front of nicknames in-game?

**Comment by BuckarooBanzay** [comment]
I'm not sure this is a good idea privacy-wise, i joined another server a year or so ago that announced a public welcome with country of origin and whatnot...
IMO: :-1:

**Comment by S-S-X** [comment]
Telling exactly who comes from what country is too much but I think having anonymous statistics about where players come would still be fine and interesting.
That would be just list of countries combined with player count for each country.

**Comment by BuckarooBanzay** [comment]
> Telling exactly who comes from what country is too much but I think having anonymous statistics about where players come from would still be fine and interesting.

Yeah, that would be ok, should even be possible with the collected logs we currently have, needs some processing though

**Comment by FeXoR-o-Illuria** [comment]
> Telling exactly who comes from what country is too much

I absolutely agree.
