### ISSUE TITLE
Easier changing names on Travelnetbox and other tools

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#212]
Vamp ; SX ; Hedgehog

Be able to change a travelnet box station's name without having to remove it and placing it back again

Added that suggestion to github issue, also extended proposal a bit to allow complete reconfiguration without need to remove + place tn box.

Can we give Telemosaic a name ?

The telemosaic thing reminds me of another idea related to names, in this case about digtrons in inventory, could they be labeled with a name that shows up when you hover cursor over it?

What do you mean by that? Name as in some text that shows up as so called "infotext", similar how text written to signs shows up on left side of screen?

Basically giving telemosaics a name, so they can be shown when hovering over one stating where it goes to ?

Would be possible but is it needed? So far I think everyone managed to survive with signs. But agreed that it would be simpler for some floor plans...

Using same infotext thing that is used by signs is simple but not that fancy, it is usable without bells and whistles. Large banner / text middle of screen is also possible but complicated and possibly asking for troubles...

Something like that would be useful for digtrons, you can know how many blocks each digtron has, but if more than one have the same number you may not be able to tell them apart

Could very well add that as digiline command because telemosaics do already have digiline support, it would not require complex stuff with formspecs.

Digtron crate naming is broken and we have github issue about that.

It is also in in-game repo, this one: https://github.com/pandorabox-io/in-game/issues/121

So the thing is digtron naming doesnt work at all? are you discussing there the best way to name digtron (either on crate or on one the components) just for simplicity or also to fix the broken naming issue?

Digtron naming works but you need to name it (crate) again every time you pack it.

**Comment by S-S-X** [comment]
Marked as duplicate because there's already been discussion about changes that could also allow changing name of station, see #206 comments.
