### ISSUE TITLE
Save the bees 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#213]
chuche952 ; SX ; 1hit ; jessicara ; Hedgehog 

save the bees
Current honey factories operate by mass-killing bees for honey. This isnt realistic and optimal. Make injector extract honey from beehive for a more humane honey machines.

You can use centrifuges to get honey without killing any bees

But is a much more complex machine.

process efficiency gets better when hive contains more honey
time = ( honey + 2 ) * 3 - honey

Though very strange, because magnetic centrifuges cant extract honey

Best: 2.5s/item 
Worst: 8s/item. 
And centrifuges are used to extract honey in real life

The principle is different with Uranium centrifuges, they dont use centrifugal force, they use magnetic field to separate heavier atoms...

Also we do not have method described available for uranium
There's multiple methods for that, you described just one possible method

You mean, in real life its possible to enrich uranium in washing machine?
Basically close to that yes.

We should be able to put all manner of livestock into a centrifuge and get out meat, hides, feathers, etc...

I'm not expert on that field so relying just on descriptions available on random internet services but you described completely different method for separation (magnetic) instead of centripetal

For me it seems we have actual centrifuges, extremely versatile ones able to handle solids and gases but we do not have mass spectrometers used for separating the isotopes

(looking for closest real life device able to handle things that technic centrifuges handle)

I refreshed my knowledge with some internet knowledge now, and indeed something like this was used in beginning. So one can use washing machine, just needs bearing replaced by a magnetic one ...

or very good mechanical bearings, made out of ... mithril?
definitely lava orbs

different device (technique) for separating things from other things sounds fun... but would be good to have enough actual use cases too.

sounds similar to mechanical deboning

About your washing machine use for enriching uranium ... there is a book that describes just that ...  The Renaissance of Renewable Energy

We should be able to put all manner of livestock into a centrifuge and get out meat, hides, feathers, etc...

Can we also make it so we can lure players in it, and watch them getting stripped of everything, including the inventory bags?

**Comment by OgelGames** [comment]
Related: https://github.com/pandorabox-io/pandorabox.io/issues/490

**Comment by S-S-X** [comment]
Closing as this already exists with in world examples and has not gained much interest besides short original discussion.
