### ISSUE TITLE
Player camera rotation

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#214]
SX ; BuckarooBanzai

So... is player camera rotation possible for mods?
Seems like no... only set_look_vertical (pitch) and set_look_horizontal (yaw) but no roll for players.
Can be done for entities with set_rotation to make other players see what is happening but victim wont feel anything

Client does not (yet) support roll data :/ too bad, it would open a few more fun possibilities: walking on walls/ceiling for example

Yeah, but also noticed my mistake there. Actually yaw is all you'd need for centrifuging players

**Comment by S-S-X** [comment]
Cannot be done with mods, requires changes to Minetest engine and client software updates.
