### ISSUE TITLE
VC in-game 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#22]
6r1d:
Recently Sivarajan proposed to do the same, by the way. He told they do it on Tunneller's abyss (hope I'm not wrong about the name and excuse me if I am). They enable voice chat for the shortly-timed events, so it's not working constantly and far easier to moderate. Some people can request some form of access, I am not sure if temporary or constant and it it's the "main" VC channel.

BuckarooBanzai
I actually had something like that planned and code in-place that logged the last geo info at login into the player metadata.... but: i ripped it out again before making the public torrents available

**Comment by Klaranth** [comment]
mohrajabi05 
Why we don't have any voicechat channel here?
Create one

SX 
because it seems there's currently not enough people interested in vc, also not sure if there's enough moderators to support voice channels

Basically voice chat moderation is way harder than text. Players of course can use voice chat, it just is not moderated by pandorabox staff and not official pandorabox feature. It could be but it is not as simple as flipping some switch to get there.

mohrajabi05 
We don't need any support for voicechannel. I told u we need a voicechannel in discord not in the game.

Hedgehog
Where is the need for it ?
When there is text, at least all comes one at a time. With voice chat, having to hear 3 or more players talk at the same time will be annoying at the least.
And don't get me started on dialects or different pronunciation.

ThinkSome
What 'we' need is Matrix, not Discord or more proprietary software and Matrix does have video and voice chat (via Jitsi I think).

SX
Yes, I was not really talking about any specific voice chat. That stands for any official pandorabox voice chat, it either has to be moderated or it cannot be officially supported.
In past there was some discussion about allowing some trusted users to handle voice chats during planned events but it was also more just brainstorming than any actual event where voice chat would have been useful. That would solve moderation part but would also be more limited for both topic and available times.
I think @6r1d was one with some ideas for handling vc officially while keeping it civil?

6r1d 
Pretty much that, open in official events as moderated

**Comment by Klaranth** [comment]
mohrajabi05 
@SX Did you agree with the plan to make a vc?
BuckarooBanzai 
I don't think thats a good idea, moderation will be a nightmare :rolling_eyes:
SX
VC would still be fine for planned events if, and only if, some trusted player(s) will handle moderation for event.
The actual event could be whatever players want, not necessarily some in game event. If someone does planning, finds other players interested in participating and presents plans how to handle it then probably also could be allowed?
@mohrajabi05 What would be your use case for voice chat? Anything specific?

**Comment by 6r1d** [comment]
Hi there. I'd say, "start with people who can volounteer to moderate at least Discord tab in Chrome", check how it goes, and only then experiment with more. :-)

**Comment by Klaranth** [comment]
Hedgehog ; ThinkSome ; SX 

Is Discord chat an option?
For voice chat it is probably currently only option with people possibly available to handle it.

Alternative : Mumble. 
Problem is simply that it wont do much else .
Voice quality vs required network bandwidth is superior, way better than TeamSpeak. Way better than Discord. Way better than anything tried so far.

**Comment by BuckarooBanzay** [comment]
My personal opinion:
* voice-chat ingame: not happening, engine-limitations and not really a primary focus of a block-game...
* discord-vc: sure why not, but we need people who moderate/listen to that

**Comment by Klaranth** [comment]
Closed by request of @BuckarooBanzay

**Comment by S-S-X** [comment]
Even if it would be wanted feature it is not something that should be discussed here because voice chat that's actually integradet in game cannot be implemented without engine supporting it and that requires everyone to update their minetest client too.
So it would anyway belong to minetest issue tracker.

**Comment by Klaranth** [comment]
The4spaceconstants 
add voice channels on this server

Alliecakes 
rush b intensifies
no stop

SX 
Been discussed few times before and so far every time decided not to. Mostly because it would need active moderators who'd actually be active on vc. I mean been considered and likely would be considered again but needs some work.
