### ISSUE TITLE
Partial mod request : h-v-smacker

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#223]
Blockhead 
h-v-smacker on GitHub maintains a technic fork https://github.com/h-v-smacker/technic that includes some cool things I enjoy over on another server: the LV sawmill, which doubles the number of planks made out of trees, and the MV thresher, which yields more from farmed crops

SX 
Blockhead, if there's some specific things (tools, machines, items, techniques) you think could be added then maybe name those. Using h-v-smacker fork as is unfortunately would be downgrade for us.

Blockhead
I just wanted to mention the LV sawmill and MV thresher from that fork for now

SX 
Would it be just LV sawmill and MV thresher? I guess we could look into that if those could be pulled into technic plus. I'll add suggestion to repository.

Blockhead
Also the lawn trimmer (trims tall grass and flowers) to trim on slopes 

SX 
Added this as issue to mt-mods/technic https://github.com/mt-mods/technic/issues/248

**Comment by OgelGames** [comment]
Issue open in technic repo, closing this one.
