### ISSUE TITLE
New tool - Angle Grinder 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#225]
Blockhead ; Hedgehog
Tool idea: angle grinder: set a circular saw shape in a menu (sneak+rightclick or something), then you can punch any block that is circular saw compatible to turn it into the configured shape. Drops an equivalent number of microblocks to what was cut off, or the complementary shape

Table saw or LV equivalent doesnt do the trick ?

The idea is to be able to modify stuff out in the field, though I'll admit it's also easy to lug a circular saw

Or use the circular saw in the hotbar and use it as a tool?

**Comment by S-S-X** [comment]
Replacer pretty much does that already?
Maybe instead better automation support for cutting nodes with existing machinery:
* https://github.com/mt-mods/technic/issues/185
