### ISSUE TITLE
April Fool idea 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#226]
Hedgehog 
April 1 Idea :  Show image of player relative to country where they live. Play from Europe, your image shows you upright as you are living close to server. America : tilted 46 degrees, Oz : upside down.

**Comment by S-S-X** [comment]
Very unlikely to happen anytime soon... and probably not useful to keep this one open.
Not even if it would be implemented next year, if interested this thing probably is better in personal todo list: _search in-game issues for "April"_.
