### ISSUE TITLE
Level up more tools 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#228]
Hedgehog ; SX 
Include levels for more tools than the current ones : e.g. glider and screwdriver.

Then glider kills you even faster and screwdriver double rotates? 
Well, durability could be thing. glider is very durable already but screwdriver not so much... or more like screwdriver has to endure a lot more activations

**Comment by SwissalpS** [comment]
Blacksmith hammer was on my mind recently. I put the thought away after realizing that then the hammer at lvl 0 would probably
only be able to repair one or two tools / armour pieces before needing repairs itself.

Similar goes for the glider and screwdriver.

Tools that don't level up are:

- lasso [mobs]
- mob net [mobs]
- bug net [firefly]
- shears [vines]
- glider [hangglider]
- blacksmith hammer [anvil]
- battleaxe [?]
- protection placer [protect?]
- screwdriver

From the above, only the **shears** seem to make some kind of sense, well battleaxe maybe too.

**Comment by OgelGames** [comment]
> From the above, only the **shears** seem to make some kind of sense, well battleaxe maybe too.

And those are the only ones that would even work, all the others are not used for digging, and thus wouldn't work with toolranks.
