### ISSUE TITLE
Mod Request Moreblocks 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#230]
Blockhead ; AceRichman
This is used on LinuxForks in their moreblocks fork (git.bananach.space/moreblocks.git).. Create a second level of compressed cobble ( 81 not just 9 ) ; the texture is flat black. Also grinding, cooking condensed cobble is also supported with some recipes there
They also have a node 'gravel on stonebrick' which is half and half.. it's used for railway ballast so that the tracks won't fall out if someone digs under a railway and the gravel falls.

https://github.com/pandorabox-io/pandorabox_custom/pull/33

Other requests regarding parts of the same mod :
#35 
#44

**Comment by OgelGames** [comment]
This issue doesn't need to exist, there's already a PR (albeit a draft).
