### ISSUE TITLE
Add digtron master builder 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#232]
Blockhead ; AceRichman ; Hedgehog ; SX 

Add the digtron master builder from Smacker's fork of the digtron mod https://github.com/h-v-smacker/digtron - copies the facing node of all builders in the digtron letting you easily set up digtrons

metatool:tronwrench -- tron wrench can be used to copy digtron settings

Isnt the difference that the wrench only copies the settings, and the builder copies everything?

It simply copies configuration for single digtron component and allows directly configuring other similar components. For example special+use on configured builder then use on builders that you want to have exact same configuration.

That doesn't perfectly overlap with the master builder, e.g. you could use it to configure a row of intermittent digger heads.

You could use tronwrench to do that bu you need to run and click on every digger head
(pretty fast but not single operation for multiple components)

The master builder doesn't do intermittent diggers, it just does builders

I think tronwrench does all components, at least it should. If it does not then feel free to complain and I'll add that..
There is no reason not to have both on here

To configure large trons you can however build production line, I think tronwrench is enabled for node breakers :)
Could add that to ideas list and see what it provides and what, if anything, is needed to make it compatible with customizations
(I don't think it is problem if fork is needed, there's been some talk about doing that anyway to get rid of many overrides)

Some other stuff in the linuxforks fork which you might look at accepting into your fork or based your fork on top of it instead of mainstream

Well, upstream has some important fixes that prevent server crashes (not utilized much on most servers but many devices on pandorabox that would cause Smacker fork crash)

mostly digtron.damage_creatures and I think there was another important but don't remember what it was...

**Comment by OgelGames** [comment]
As mentioned, the tron wrench exists for this purpose. Closing this.
