### ISSUE TITLE
Additional usage of /search  

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#233]
Number_Six ; Hedgehog 
/search could be useful to search names of teleport tube channels

There is a public channel list in the wiki

**Comment by BuckarooBanzay** [comment]
The `/search` command is part of the mapserver mod (https://github.com/minetest-mapserver/mapserver_mod/blob/ad4e151184bc4abb3087b8fd45377accc88c0114/bridge/search.lua#L192)

In order to enable the search for them the tp-tubes have to be added to the mapserver-database for indexing/collecting (called `mapobjects`: https://github.com/minetest-mapserver/mapserver/blob/master/mapobject/setup.go)

Another way would be to implement another chat-command in the pipeworks mod itself (for reference: https://github.com/mt-mods/pipeworks/blob/master/teleport_tube.lua)

The `pipeworks` command would be more sane and simple in my opinion.

**Comment by SwissalpS** [comment]
the metatool for tubes already offers search. Place a tp-tube and insert the channel you are looking for. Use tool on it with modifier key and it lists targets with coordinates.

**Comment by S-S-X** [comment]
> the metatool for tubes already offers search. Place a tp-tube and insert the channel you are looking for. Use tool on it with modifier key and it lists targets with coordinates.
> 
> Edit: The tool also already filters out tubes that player can't use.

This could also be extended with tubetool search command removing need to place and configure tube but still require tool to do search:
Could allow opening formspec with empty tool and ask for channel then list locations for that channel, then display teleport tube listing for that channel.

Currently tool protects teleport tube locations on private channels by simply requiring player to actually find configured private teleport tube, this is good imo and if freeform tube lookup would be added for tool (or as chat command) then I think it should be restricted to public and owned channels.

**Comment by OgelGames** [comment]
I think the functionality that was requested is being able to search for public channels that have receivers, to find a suitable channel to send excess items to.

For example, one could search "cobble" to find what channels they could send cobblestone to.

**Comment by SwissalpS** [comment]
would be cool if luac could querry too, so we can make the lists, currently on posters, dynamic consoles to list and search with.

**Comment by S-S-X** [comment]
For that stuff (to find tp tube channel that should be used for excess items) some bot command could give these: https://pandorabox.io/index.php/Overflow_tubes#List_of_Channels

**Comment by S-S-X** [comment]
This issue probably is not really needed:
* does not seem to have that high demand.
* if it is not in wiki then it probably isn't significant and possibly not maintained.
* sometimes channels are meant to be quick temporary solution hidden from others while in use.
* wiki can be used as a source and player can copy lists from wiki to book.
* if needed books can be cloned and afaik also updated in game.
* any player can create in-game list with wiki+luac+nic+lcd or similar.
