### ISSUE TITLE
Rename of XP sublevels?

### ISSUE THREAD

**Issue by kiedtl** [pandorabox-io/in-game#237]
I'd like to suggest renaming the sublevels of the XP ~~pecking order~~ ladder. I don't particularly like the current one (why is "mayor" before "master", and why is "lord" below "mayor"?), but that's obviously a matter of taste more than anything else (at least its better than the US army one used before). Maybe we can see some ~~fun bikeshedding~~ discussion here on getting more "intuitive"/better level names.

Currently, the levels are:

- peasant
- merchant
- knight
- lord
- mayor
- master
- god

Some suggestions:

Nobility (probably unintuitive for those who aren't familiar with British nobility -- does a "count" come before or after the duke again?):
- peasant
- baron
- lord
- earl
- count
- duke
- king

Cleric:
- initiate
- monk
- cleric
- priest
- bishop
- pontiff

DnD-inspired (sorta...):
- caveman
- hunter
- cleric
- warrior
- mage
- wizard

**Comment by birdlover32767** [comment]
nobility would be best because it also has 7 subranks

EDIT: here is mine (based on skill-level)

* beginner
* amateur
* apprentice
* adept
* expert
* master
* grandmaster

**Comment by birdlover32767** [comment]
btw unrelated, but the major ranks (gold, diamond, etc) don't make sense either
currently it's like this:
* cobble
* stone
* coal
* iron
* copper
* gold
* diamond
* mese
* lava
* sulfur
* uranium
* chernobylite,
* corium
* mithril

why is copper after iron, mese after diamond (diamond tools are better),  why do sulfur, uranium, chernobylite and corium exist as ranks at all????

my proposed major ranks are:
* wood
* cobble
* stone
* coal
* copper
* tin
* iron
* bronze
* silver
* gold
* mese
* diamond
* lava
* mithril
or if you don't like wood, just throw <insert technic ore/alloy here> or obsidian in
