### ISSUE TITLE
XMPP Server integration? 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#241]
GamesBond ; wsor ; SX 
Will there be an XMPP server integration for pandorabox? XMPP is a neat protocol and there is a server package named prosody which is written in lua. Should be easier to integrate, I guess.
Also, the clients are lighter than discord. Mostly no JS.
Except for a few webclients

wsor:
oh great, the clusterfuck argument of add support for xyz chat protocol is going to get started again 
my only comment on the subject at this point is https://xkcd.com/927/

Currently there's IRC which is lightweight option. XMPP probably would be fine but probably not enough demand for it, ofc could add PR for beerchat proxy or work on matterbridge proxy to make missing things work with it so that beerchat-proxy could be replaced with matterbridge...

Only problem with matterbridge seems to be that there's no way to send messages to only single selected endpoint / private channel for commands and such

**Comment by OgelGames** [comment]
If any other chat platform is going to be supported, it will be using matterbridge: https://github.com/pandorabox-io/pandorabox.io/issues/699

I see no reason to have any other issues open about this.
