### ISSUE TITLE
ATM reduced trashcan ability 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#243]
Huhhila
Make ATM reject non-minegeld items from tubes instead of acting like a trashcan (which it currently does even when given a stack containing 4x currency:minegeld_cent_25)

**Comment by OgelGames** [comment]
Hmm, it should be a simple fix, but currently we are on 6r1d's fork of the `atm` mod: https://github.com/6r1d/atm/tree/master Maybe it could be moved to `mt-mods`?

**Comment by SwissalpS** [comment]
From the last conversations I've had with Grid, he's got more important things to do atm.
@6r1d would you mind to comment?
(maybe discord or /mail ping is required to get his attention)

**Comment by 6r1d** [comment]
> maybe discord or /mail ping is required to get his attention
Hello. Not really, I'm here.

> 4x currency:minegeld_cent_25
Hmm, it's awkward it destroys money at this point.

I totally should log in and patch this up. Not sure at which day, but I'll remember that! :)

**Comment by SwissalpS** [comment]
> acting like a trashcan

I could not reproduce this when adding coin support. https://github.com/mt-mods/atm/pull/2
Items that aren't valid currency are rejected and sent back through the tube they came in.

Now stacks of coins are accepted, any decimal leftovers are returned. (once the changes become active on live server)
