### ISSUE TITLE
Compressing charcoal to get coal

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#245]
baijin
Compressing charcoal to get coal
Maybe filtering out the wood gas and residues first, then taking what's left and squishing that

SX 
compressing charcoal to get coal is bad idea as it further reduces items that can mostly be obtained through active work

See also #46

**Comment by OgelGames** [comment]
Yeah, not happening. (and I'm fairly certain that Buckaroo would agree)
