### ISSUE TITLE
Smarter injectors

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#247]
baijin
smart injectors that don't push items into full containers

Hedgehog 
Just put enough chests in line able to receive, and problem solved.

**Comment by S-S-X** [comment]
There's multiple different approaches to get around full inventory problem, there is still problem in pipeworks with injectors pushing into wrong containers.

To fix pushing stacks into target that is not right in front of injector I do think it would be way better to destroy stacks if target cannot handle incoming stack. That would both fix bug and make players think how to build factories.

It would also make target inventory to behave as trash can which in my opinion is not exactly best possible behavior but it is probably cheapest possible behavior. Dropping stacks to ground would be another possibly more correct option but again not sure if that's good idea. Not doing anything like suggested by baijin would fix issue but in my opinion is not good solution as there's already other ways to make injector skip operation or bypass target inventory.

Anyway I think original request should not be implemented as is and probably should not be implemented at all other than through fixing injector bugs (undocumented, counterintuitive and seemingly unpredictable things).
Bugs should be tracked in pipeworks repo and are not valid reason to keep this issue open.

**Comment by S-S-X** [comment]
This most probably wont be ever implemented as a server customization and is not strictly required for anything, described goals can already be achieved with existing functionality / items.

If needed discussion can be moved to / restarted at https://github.com/mt-mods/pipeworks/issues as a new feature request / bug report.
