### ISSUE TITLE
Debug Lua upgrade -- was: Internal Error Message Trace added 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#248]
baijin
The internal error message should include a debug trace of the failing mod and function

BuckarooBanzai 
2022-01-01 21:17:21: ERROR[Server]: /git/minetest/src/script/cpp_api/s_base.cpp:8c: static int ScriptApiBase::luaPanic(lua_State*): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (bad argument #4 to '?' (userdata expected, got nil))
https://pandorabox.io/crashlogs/crash_2022-01-01_21-17.txt

**Comment by OgelGames** [comment]
Yeah, not an idea, just a statement...

**Comment by Klaranth** [comment]
Huhhila
Another idea, for luac: add some kind of wrapper for debug.lua_gethookcount (and/or debugging/profiling features in luatool instead of luac itself, but that could need far more effort)

**Comment by S-S-X** [comment]
Created new issue from last comment, this issue was about server mod execution environment and new idea is about in game lua controller.
