### ISSUE TITLE
AdvTrains Rockets

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#25]
y5nw (ywang) — 03/23/2021
Hmm, someone should design rockets for advtrains

SX — 03/23/2021
could just create mod similar to linetrack, that is custom rails for advtrains. well I'm not sure if advtrains can follow vertical lines or if there's some built in limits
after that... draw rocket model. or just borrow some existing model

**Comment by Montandalar** [comment]
Advtrains tracks have to have a horizontal component although they might be unlimited in the vertical component. e.g. have a 500 metre height gain but 1 metre horizontal movement. You could probably take the rocket model from [nodeverse](https://content.minetest.net/packages/aerkiaga/nodeverse/).
