### ISSUE TITLE
Mailbox vs Wifi chest 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#250]
Hedgehog
Have all of a player's mailboxes be linked together. So that, from any one mailbox, they all put items in a central storage.
And from any one mailbox they all can dip into that one storage.

Gorlock
That's wifi chest
Also keep the possibility to have several mailboxes

SX 
also make it use few more nodes because it is way more powerful than simple mailbox or wifi chest. Well, I guess I just told you to build that from chests, injectors and teleport tubes...

See also #197

**Comment by OgelGames** [comment]
It's possible to build this, no need to mess with mailboxes.
