### ISSUE TITLE
skinsdb support mapserver 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#253]
Blockhead
is skinsdb support for mapserver something sensible?
Huhhila
I think there is already an issue open about highscore being bandwidth hog because of skinsdb...
SX 
aggressive caching would solve that and could be done by just adding proxy so mapserver would not need to implement special caching itself
even squid proxy would be fairly simple for that
varnish with filesystem only storage and some simple proxy like stunnel would also be fine (should be more efficient with less wasted server resources)
I think even haproxy would manage it just fine but I think it allows only ram based storage and is extremely simple for caching server side
probably simplest well supported and very flexible solution would be varnish + https proxy for outgoing requests
outgoing proxy could ofc be current proxy that is already handling incoming requests which is nginx
maybe nginx could also be directly used as caching proxy, not sure about efficiency / what it allows. never done, only actually played with other mentioned solutions.

**Comment by Klaranth** [comment]
Huhhila : link to [pandorabox.io#686]

**Comment by OgelGames** [comment]
https://github.com/minetest-mapserver/mapserver/pull/284
