### ISSUE TITLE
Improve on infinite diamond generator

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#259]
baijin
Putting wood charcoal through the refinery to create a slurry, which goes through an extractor to chemically separate the carbon molecules and chains, and another extractor, then a centrifuge to remove the radioactive carbon isotopes, then it turns into coal dust

**Comment by SwissalpS** [comment]
https://github.com/pandorabox-io/in-game/issues/245

**Comment by Baigle** [comment]
its not meant to be

**Comment by S-S-X** [comment]
Pretty much same comment: bad idea as it further reduces items that can mostly be obtained through active work.
Exact duplicate of #245 with just different process details.
