### ISSUE TITLE
Increased hand tool capability (High XP players)

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#26]
wsor — 03/29/2021
would a longer range and/or increased hand tool capabilities be of interest for higher ranked players?

BuckarooBanzai — 03/29/2021
A replacer with longer range would be neat :think:

wsor — 03/29/2021
thats a tool, so simple fix....
just edit range = x
if you made a longer ranged hand it would edit the default range of all tools
anyways, no interest then? fine by me

SX — 03/29/2021
imo range for tools is very high already and increasing it further is not exactly required for anything

wsor — 03/29/2021
if tools have a longer range than hand, it uses that range
im suggesting making the hands range longer, not tools

SX — 03/29/2021
how long is your hand actually....?
like it does not have to be that realistic but nice if it stays somewhat sane, just my opinion but imo hand range should never be even near any tool range
well maybe some small tools like drill could have shorter range similar to hand but like hand should have shorter range than shovel
for building I think increasing replacer range a bit could actually be good

**Comment by S-S-X** [comment]
Would it be good having even longer range for replacer?
It could help a bit with building as tool allow placing nodes.

For technic replacer probably better to not increase range to keep it just tiny bit safer but possibly for regular non technic replacer.

**Comment by S-S-X** [comment]
Technic replacer already uses metadata and could also have configurable reach distance option with some upper limits (through already existing formspec).

**Comment by OgelGames** [comment]
For some reason reach (range) is not part of `tool_capabilities`, so I don't think it's possible currently...
