### ISSUE TITLE
Technic.conf introduction 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#261]
Huhhila
Should https://github.com/pandorabox-io/pandorabox.io contain a technic.conf or are we happy with defaults? (see for example ../pandorabox.io/pull/607 and technic/pull/257)

**Comment by S-S-X** [comment]
As a generic question this is not really useful and imo could be closed.

If there's problem with some feature, something should be adjusted, something should be enabled or something should be disabled then better to create new more specific issue about that.

We could be happy with many possible configuration combinations but if there's no specific reason to change it then it probably is good already.
