### ISSUE TITLE
Introduction new skins - Hedgehog / Sonic etc 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#263]
1hit 
Naso, could you make a skin for the skinsdb that is a hedgehog?  Either life-like colors or Sonic style? Would totally be funny if Hedgehog (the player) could skin as a hedgehog

Hedgehog 
I approve this request. 

Naso 
I think there should be plenty of sonic player skins already out there. A lifelike hedgehog skin sounds fun tho, could even make use of the cape to give spines volume. I'll think about it. Incidentally, I have a skin of my own that I'd like to have in the server's wardrobe but I have no idea how to go about it :3
Hmm, I'll move the question somewhere else, as it happens I usually need a lot of help with stuff :P

Hedgehog
Nono .... We add the Q and A to the github ideas section, as it all ends up in there anyway.  

Also, I might think here would be a good spot to add the skin to it, but I am not too certain about it : https://github.com/minetest-mods/skinsdb

**Comment by Klaranth** [comment]
AceRichman
you can just send it to Buckaroo to add it to the server, that's how I got mine added
though if we want to make it easier for the future, maybe the skins directory could be git-ified to a pandorabox_skins repo... 🤔

wsor 
if you really wanted you could only load per player skins when they join with dynamic media

AceRichman
as for hedgehog skins, there's a sonic skin on skinsdb: http://minetest.fensta.bplaced.net/#name=Sonic%20The%20Hedgehog
or there's a bunch of minecraft skins: https://www.minecraftskins.com/search/skin/hedgehog/1/

Naso
well I got my skin on skinsdb and the skinsdb mod is here so I suppose all there is left is to ask for it to be pulled. Is that easier? Idk

**Comment by SwissalpS** [comment]
> maybe the skins directory could be git-ified to a pandorabox_skins

👍🏼

**Comment by OgelGames** [comment]
The hedgehog skin has already been added, and I opened a separate issue for the skins repo idea: https://github.com/pandorabox-io/pandorabox.io/issues/733
