### ISSUE TITLE
Vending machine Recipes 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#267]
cyriax 
Not sure if that's the right channel for it, but there are these uncraftable vending machines (home_vending_machines:drink_machine and home_vending_machines:sweet_machine). Is it possible /wanted  to set up admin-shops at spawn for them?
SX 
Possible but maybe it would be better to add recipes instead.
cyriax 
That would be even better. Not sure where they are from and how easy it is to get it upstream.
SX 
We are basically upstream nowdays
cyriax 
Ok, I'll think of something and get back to you.
SX
https://github.com/mt-mods/home_workshop_modpack something similar to soda machine would probably be good (crafts: https://github.com/mt-mods/home_workshop_modpack/blob/master/home_workshop_misc/crafts.lua)
basic_materials stuff would probably also be fine for recipes, homedecor stuff uses it anyway for many things
but not really that limited as alternative recipes can be added. crafting recipes wont need mods to be added as dependencies anyway

cyriax 
Pull request is open.
https://github.com/mt-mods/home_workshop_modpack/pull/5

SX 
wsor will prob want to comment that at some point... I guess we can get recipes merged soon. improvement anyway and wont probably really affect current refactoring efforts wsor been doing

**Comment by S-S-X** [comment]
Added in https://github.com/pandorabox-io/pandorabox-mods/pull/2142
