### ISSUE TITLE
Quarry interactions > Beacon beams

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#271]
Huhhila
Make quarries interact in some way with beacon beams and bases, where "some" does not necessarily have to be similar to digtrons.

**Comment by SwissalpS** [comment]
Do you have any concrete suggestions, I quite like how it is. Maybe I would change my mind if I knew what you were thinking of.

**Comment by Klaranth** [comment]
> 

If you want an answer from Huhhila, do ask ingame.

**Comment by OgelGames** [comment]
I see nothing wrong, beacon beams are not diggable, so quarries don't dig them.

**Comment by Klaranth** [comment]
FeXoR
The quarry's mesecons support is pretty dangerous and should IMO be turned off by default.

Huhhila
FeXoR: except in the corner case of (has_digilines == false) and (has_mesecons == true) ... which currently has no method for the mesecons to do reset_quarry (nor just setting dug to -1), since that is only called from digilines and on_construct.
(besides the formspec that is)

**Comment by OgelGames** [comment]
I think this should have been put in a separate issue, it has nothing to do with beacons... Probably should move it to the technic repo.

**Comment by OgelGames** [comment]
Ah, thanks, was about to copy it over myself :)
