### ISSUE TITLE
Changing Beacon options 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#273]
Hedgehog
Changing water breathing option in beacons into not suffocating, and make it possible to use beacons to breath in vacuum as well.

Huhhila
I'd say keep it as it is, no need to make space easier than it already is.

Hedgehog
Still need to add a lot of beacons and a lot of diamonds to make it 'easier'
Not sure I want the game to be safer, but you (Huhhila) planted that seed in my mind about breathing in vacuum being the same as breathing underwater. And with the spacesuit working for both that makes some sense.

**Comment by SwissalpS** [comment]
This was discussed when beacons were re-written. The consensus was pretty much what Huhhila said.

**Comment by OgelGames** [comment]
Yeah, no.
