### ISSUE TITLE
Spheretest mod

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#28]
sunks — 04/04/2021
wonder if there could be like other dimension with items copied over with spheretest playing and one with normal Pandorabox, but then it might eat items too and spheretest's long dead, it makes real planets sphere and all in Minetest

BuckarooBanzai — 04/04/2021
The "spheretest" modifications were mostly on the client-side, you might be able to port them to 5.x and connect with your client :wink:

**Comment by S-S-X** [comment]
I think this is basically impossible to implement only server side and because of that also impossible to add to existing server without breaking client compatibility.

That makes it practically impossible to do with existing server and player base even if it would be possible in theory.

**Comment by OgelGames** [comment]
Closing as per SX's comment.
