### ISSUE TITLE
Mod request : Nether  

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#281]
Outerspce
I think the nether is a great thing and mobs in it as well
https://github.com/minetest-mods/nether

y5nw (ywang) 
I suppose it depends on the complexity of the mod and what it changes, among other things

Hedgehog 
And how much of the existing mods break because of it :P

SX 
One important factor: how easy it is to remove mod after adding it
Some things can be just tested if it is easy to remove, if it is not that easy to remove / requires some cleanup then some work is needed to determine compatibility and more testing has to be done.

Sometimes not updating ever means that it already has everything while sometimes it means that mod is broken and not supported
Have to look at content / quality instead of age / commit count. Sometimes we can adopt mod that is abandoned / not supported anymore.

**Comment by OgelGames** [comment]
It's something to consider for the "world expansion", but I'd prefer something more unique like Morlendor.

Probably could just close this and copy it to #8

**Comment by S-S-X** [comment]
As a little bonus, if added, NSSB Morlendor portals in my opinion are also better than Nether portals.

**Comment by Klaranth** [comment]
Outerspce
What about the nether gets a nether portal?
We have nether boots aka crystal boots but needs the nether
