### ISSUE TITLE
vector.new expose 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#282]
Huhhila
expose vector.new to luac (may need to limit vector.metadata access?); would be most useful once https://github.com/pandorabox-io/pandorabox.io/issues/711 is live on main server

Engine/Game migration Image: https://github.com/pandorabox-io/minetest_docker/releases/tag/5.5.0-r1 (based on 5.5.0 upstream tag) Notable changes zstd map format (should increase performance)

**Comment by Klaranth** [comment]
Engine/Game migration Image: https://github.com/pandorabox-io/minetest_docker/releases/tag/5.5.0-r1 (based on 5.5.0 upstream tag) Notable changes zstd map format (should increase performance)

**Comment by OgelGames** [comment]
There's a bunch of stuff that could (and should) be available in the Luacontroller sandbox (see https://github.com/minetest-mods/mesecons/pull/507 for some of them). I don't think there needs to be an issue here about it.

**Comment by OgelGames** [comment]
Closing in favor of #290, doesn't need a separate issue.
