### ISSUE TITLE
Building an EscapeTest mod 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#285]
mrminer
"EscapeTest" - mod for building escape rooms

Hedgehog 
Is this an existing mod?

SX
I guess that would just need "no escape zones", preferably only activated through mission. I think there might already be issue about teleport restriction zones.

**Comment by OgelGames** [comment]
This is probably possible with the `epic` mod on the Damocles minigame server (Buckaroo's other server), I don't think a specialized mod like that would suit Pandorabox though.

If the only problem is preventing players from teleporting to the end, you could just place several waypoints.
