### ISSUE TITLE
Technic charge for radar 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#287]
SX 
Technic charge for radar, long lasting something similar to headlamp.
Allows old mapping kit to have some small advantage other than just different recipe, simply pay more for better item is bit boring concept.

Huhhila
On the other hand inventory micromanagement is also more boring than actually doing something with the world.

SX — 05/22/2022
Maybe something else but then also there should not really be that much micromanagement if it last as long as headlamp. Having battery charge however sounds like most correct option for device itself.
(automated recharging station could be used to reduce micromanagament, works pretty with other tools too)

Huhhila
Yup... guess I'll have to bite the bullet and finally utilize mithril chest's move all to chest / move all to inventory for automated repair/recharge of everything in inventory, as well as recycle/store anything that doesn't need to be there...

**Comment by SwissalpS** [comment]
unlike headlamp, you don't even need to open armour inventory.
+1 for radar using charge

**Comment by S-S-X** [comment]
Reopening for possible discussion as at least few players agreed that feature might be good. Add "possible close" tag if it seems appropriate.
