### ISSUE TITLE
homew alias to /home

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#293]
MCLV
Let's make /homw an alias to the /home command. that way I don't have to move my fingers from the asw position when I'm panic teleporting ;)

Huhhila
MCLV: With similar sound effects to /msg:ing yourself?

MCLV
We don't have nearly enough funny commands

a
Also, the keyboard arrangement of /home isn't as much of an issue if you use Dvorak, as you should :P

**Comment by S-S-X** [comment]
This is one of those things that generally should not be implemented server side without very good reason but instead should be client side.
Might be doable with CSM API.

**Comment by OgelGames** [comment]
Yep, it is possible to do with CSM, but only if the `csm_restriction_flags` allows for sending chat messages, which by default it doesn't.
```lua
local aliases = {
	["/homw"] = "/home",
	["/homer"] = "/home",
	["home"] = "/home",
	["spawn"] = "/spawn",
}

minetest.register_on_sending_chat_message(function(msg)
	if aliases[msg] then
		minetest.send_chat_message(aliases[msg])
		return true
	end
end)
```

**Comment by Klaranth** [comment]
Does that code include a soundbite for /homer ?

**Comment by OgelGames** [comment]
> Does that code include a soundbite for /homer ?

That could be added, though custom sounds are not supported, so you would have to use an existing one:
```lua
minetest.register_on_sending_chat_message(function(msg)
	if aliases[msg] then
		if msg == "/homer" then
			minetest.sound_play("beerchat_utter", {gain = 0.3})
		end
		minetest.send_chat_message(aliases[msg])
		return true
	end
end)
```

**Comment by SwissalpS** [comment]
just reasign your movement keys to 'wsdf' so your hands are always in standard typing position :)

**Comment by MCLV-pandorabox** [comment]
I totally love the code "solution". I mean, who doesn't love code eh?
But it works only if csm_restriction_flags allow it, which it does not on pandorabox.io, so it is not a solution.

SwissalpS proves once again that the real solution to the problem might not lie in the all-mighty code. 

Thank you all so kindly for your contributions to this little silly question.
I'll let you get on with more serious matters, while I try out my new key configuration.
