### ISSUE TITLE
Introducing parts from Exile 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#295]
Based on an idea from sunkenhero in the main channel, I looked into weather mods and found this one:
https://content.minetest.net/packages/Mantar/exile/

According to Ace, this is not a mod, but a whole new game/server. However, wouldn't it be interesting to introduce hypothermia and such ? Is that even possible?

**Comment by Klaranth** [comment]
Adding to Silly Ideas and closing this one?

**Comment by OgelGames** [comment]
Not quite silly enough, but I do think we should close this, I doubt anyone wants any more sources of damage.
