### ISSUE TITLE
Adding Transparent Textlines

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#30]
Emojidiscord — 04/22/2021
https://github.com/gbl08ma/textline/pull/7 @BuckarooBanzai @S-S-X this version was merged into textline matter, contains transparent text line and few bugfixes
GitHub
Add Transparent Textline (textline:hud) by Emojigit · Pull Request ...
Close #3

SX — 04/22/2021
Very nice, don't have to rotate those anymore to get working hud. Rotating also caused problems if text entity got destroyed for whatever reason..
BuckarooBanzai — 04/22/2021
nice :thumbsup:

**Comment by OgelGames** [comment]
Already exists, but needs crafting recipe.

**Comment by S-S-X** [comment]
As this is not really new idea and there will be no discussion about it other than possible items for recipe (and that is simple too as it should be similar to textline lcd) I've created implementation issue https://github.com/pandorabox-io/pandorabox.io/issues/663
This can be closed.
