### ISSUE TITLE
Nodered API suggestions  

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#307]
Huhhila
/nodered/api/areas/by_id/:id or /nodered/api/areas/:id/by_id with same functionality as the :user, just filter by id (use case: read specific area info with luac+nic)
Or just rename :user to :key and have a query-string switch for determining key type, defaulting to :user for compatibility

**Comment by SwissalpS** [comment]
not as clean as Huhhila suggested, but should work:
https://pandorabox.io/api/areasid/1?format=html

**Comment by SwissalpS** [comment]
player nicks can be just numbers, so just checking for that wouldn't work.

**Comment by S-S-X** [comment]
Seems like this has been available for some time already and can be closed as completed.
