### ISSUE TITLE
The XP system can be annoying

### ISSUE THREAD

**Issue by the-pumpkin-man** [pandorabox-io/in-game#309]
The XP system, instead of something being either fun or something to protect from griefing, is sometimes just annoying. Here are the privs which I don't understand why they are restricted:
- moon_access (10,000 XP) Access to the Moon
- asteroids_access (20,000 XP) Access to the Asteroids
- mars_access (50,000 XP) Access to Mars

What is the point of restricting these ? Especially that the server is centered on space, so it makes sense for new players to at least be able to see what space looks like (from a safe spot in say the moon station, if they don't have any spacesuit).
Here are the arguments I've seen so far with my refutations:
- Noobs will put cobble on the Moon/Griefing: well, they can do that on Earth too. Why would you discriminate Earth ? Just put an XP  cap on Earth too, so noobs won't be able to put cobble there ;)
Actually this is the only one I remember, tell me if you have other arguments.
Then I don't understand, why are you putting different caps for Moon, Asteroids and Mars ? Why don't you just put the same cap for the 3, if any cap at all ?

Then here are privs I'm not too sure about:
- areas_protect (10,000 XP): You can't protect with areas below 10k xp, but you can with protection blocks ? It's a bit prone to griefing if you decide to build without protections and wait to get 10k xp because you don't like how protection blocks mess with your builds. Maybe if you're afraid of annoying people protecting large zones for nothing, allow to have areas_protect but for very small zones, and then give this one at 10k xp as you do.
- lavastone_remove (40,000 XP): This one is to recover against people griefing with lava and water. Then why is there an XP cap on it if it can only be used for a good thing ?
- Place uranium (50,000 XP) *: I perfectly understand why there is this XP cap, as uranium is very radioactive and could be very annoying to people if placed at the wrong spots and used carelessly, but on the other hand it's a very useful block to protect against corium radiations, so I would like to have it for myself.
- missions_teleport (300,000 XP): Why is it even restricted ? After all, there are telemosaics already freely available. It just gives the option to freely tp to people with 300k XP and those who don't are annoyed.

The rest I agree with as it's to prevent from too much lag or from griefing.

A general problem with the XP system is that it gives you xp only based on placing blocks and breaking blocks, and it's only 1xp per broken/placed block no matter what. I don't really see a better alternative metric to distinguish regular people from griefers, but it could be nice maybe to give xp based on broken blocks. Like giving more xp when digging a diamond ore for example. The only issue would be then if you're able to place diamond ores, as you could repeatedly place/destroy them. When progressing in the game, at some point you don't dig anymore but use digtron/quarries, which also removes xp gained by digging, but I suppose that then you still have the option of placing blocks.

**Comment by S-S-X** [comment]
Check out https://pandorabox.io/index.php/Gameplay_rebalance_June_2019

> areas_protect (10,000 XP): You can't protect with areas below 10k xp, but you can with protection blocks ?

Areas causes multiple problems without some XP restrictions and have been used for griefing, without significant updates to areas mod it cannot be without XP restriction.

> lavastone_remove (40,000 XP):

This... not really sure. I think it should either be admin only or no very low XP requirement. Well, it does somewhat expensive search server side... could be in attempt to limit use and not allow using up server resources with starter account.
Command however could fairly easily implement cooldown timer to prevent that...

> Place uranium (50,000 XP)

In past we've seen a lot of uranium traps around public areas that are assumed to be safe, this is kind of must have restriction.

> missions_teleport (300,000 XP): Why is it even restricted ?

This is completely different than any other travel mode, it is closer to admin teleport than other things.
For one it allows teleporting into protected areas owned by other players.

> Like giving more xp when digging a diamond ore for example.

Long time ago this was a thing but it wasn't good so it was removed.

> When progressing in the game, at some point you don't dig anymore but use digtron/quarries, which also removes xp gained by digging, but I suppose that then you still have the option of placing blocks.

Yes, it is expected that you'll be building a lot more (and not just regular structures) after you actually are able to use digtrons and quarries. Still many who can use only machines are actually still doing a lot of manual digging.

**Comment by OgelGames** [comment]
I think this can be closed, haven't heard anyone else complaining about the XP system. If anyone does it can be reopened.
