### ISSUE TITLE
Travelnet improvements

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#314]
Currently Huhhila and Hedgehog ran into some difficulties. 

We found a combination of the following problems:
1 - Unconfigured travelnets can be configured by anyone regardless of protections.
2 - Travelnet owned-by can't edit/detach/remove a particular travelnet unless current permissions of the area/node location allows that. 
3 - somewhat misleading error messages when the protection violation attempts happen. 

For more information, or deeper explanation, please contact Huhhila in-game.

**Comment by OgelGames** [comment]
This may have been fixed by now, would need to do some testing to confirm it.
