### ISSUE TITLE
[Addition] Hammermod

### ISSUE THREAD

**Issue by Monniasza** [pandorabox-io/in-game#315]
I'd like to have Hammer mod added, to speed up mining:
https://content.minetest.net/packages/cultom/hammermod/

**Comment by S-S-X** [comment]
There's currently Technic mining drills which cover 3x3 nodes per use.
Then there's tool ranks which makes certain tools extremely fast at max level.

For me this sounds a lot like mining drill mk3 which you can already craft and use.
Power banks provide mobile recharging ability.

**Comment by Monniasza** [comment]
There's also pandorabox-mods# 2867 , which is the same

**Comment by S-S-X** [comment]
For Buckaroo's question

> Does the hammer in that mod even wear out? 🤔

It does wear out but rate is apparently only small fraction of what it is for other tools. I've not actually tested it.
Wear is however same for every possible node, code is fairly simple: https://github.com/cultom/hammermod/blob/master/init.lua

**Comment by OgelGames** [comment]
We already have mining drills for this, and I don't think we should add a cheaper way to do the same thing. Also digtrons.

**Comment by Monniasza** [comment]
The mod appears to be abandoned. It should be forked and rebalanced.

**Comment by OgelGames** [comment]
> The mining drills are inconvenient because they need to be brought back to the station

Which is exactly what `powerbanks` were created for.
