### ISSUE TITLE
[Addition] MicroExpansion

### ISSUE THREAD

**Issue by Monniasza** [pandorabox-io/in-game#319]
After a talk on Discord, I request Microexpansion to be fixed up and added to the Pandorabox.

Microexpansion is a storage mod allowing to centrally manage a storage system comprised of ME Cells, and thus providing greater capacity than a simple chest storage system.

Mod link: https://content.minetest.net/packages/theFox/microexpansion/

**Comment by S-S-X** [comment]
Anyone can explain how this actually works, CDB page isn't really useful and mod repo also doesn't really tell much more than just _increases chests capacity_? Based on descriptions it seems to be increasing chest sizes somehow and probably wants some tube/cable like nodes that apparently connect to some other no-idea-what-they-are-nodes to do something.

There was talk about forking it but wsor pointed out that mod author is still active so it would be better to submit pull requests to https://github.com/theFox6/microexpansion

**Comment by Monniasza** [comment]
@S-S-X Submitting PRs requires forking the repo. The Pandorabox can maintain its fork in addition to the mod author's original

**Comment by SwissalpS** [comment]
From first read, it sounds a lot like more compact drawers.
Then "adds many nodes" scares me a little.
Looking at the api-docs, I'm not sure if it needs all items to be registered through it or if that is just to add more ores to mapgen. (or add meta and change textures)

I'll have to take it for a test-drive sometime...

**Comment by SwissalpS** [comment]
> Anyone can explain how this actually works,

yeah, even the docs use a lot of words to not say very much. :D

**Comment by SwissalpS** [comment]
this mod is not ready for production, just crashed my game

**Comment by SwissalpS** [comment]
As far as I can tell from playing a bit:
- needs a lot of fixing up. e.g. I could not figure out how to remove cables.
- It is a lot like drawers.
- Needs:
  -  a network controller (switching station, but adding multiple can destroy all your stored items)
  - 1 to ? many drives (cabinets)
  - each drive can be fitted with up to 10 storage cells (upgrades)
  - storage cells come in different sizes. 64k being the biggest so 640k per drive (cabinet)
  - you use one or multiple terminals to input/output the items
  - terminals have a search feature
  - networks are connected by placing nodes next to each other (similar to drawers) or you use cables
- mix between drawers and technic network
- unlike drawers, items of various types can be stored
- huge stacks way over item_def.max_stack size
- I have no clue what a fuel-fired-generator is supposed to do

judging from an issue title "needs limits" I'm guessing you can expand until end of universe

bottom line: not ready

**Comment by Klaranth** [comment]
> Oh and the fuel-fired generator is supposed to power the storage network, but it seems like that part is not implemented yet (among other things)

So we need to keep fueling it, or it will use the content to keep itself active? :)

**Comment by OgelGames** [comment]
Ideally there would be an "exporter" node that you could place on the side of the generator and configure to put fuel into it from the network.

**Comment by SwissalpS** [comment]
Yes, what you are saying makes sense. LV power and tubes.

Before anything like that happens, there are a lot of bugs and there must be limiting of some way added :) I'd rather take up drawer rewrite again than help with this mod.

**Comment by Klaranth** [comment]
Monniasza 
Hedgehog has a lot of stuff. Please add MicroExpansion: https://content.minetest.net/packages/theFox/microexpansion/

OgelGames 
I already crashed it :P
AsyncErr: Lua: Runtime error from mod 'microexpansion' in callback ScriptApiDetached::detached_inventory_OnTake(): InventoryList 'main' is currently in use and cannot be deleted or resized.
 
Monniasza 
@OgelGames MicroExpansion needs to be forked

Klaranth
Also, the mod states it is all about lots of chests. Doesn't say anything about lots of drawers.
OTOH, if this can be made workable on Pbox, @MCLV might have a perfect solution to work with for Salvation :)

MCLV 
Hmm 'store thousands of items' hardly seems enough. Anybody got the details of the exact numbers?

Monniasza 
@MCLV It depends on drives installed

BuckarooBanzai 
Had this issue myself with just the moreblocks mod, its an engine problem on the master branch currently

Huhhila
Appears to be buggy... are you volunteering to fix all those bugs? :)

BuckarooBanzai 
Microexpansion items aren't protected it seems: https://github.com/theFox6/microexpansion/issues/11

Monniasza 
I've told that it needs to be forked

SX 
Would you like to do that and work on issues it has? That could definitely help. Of course if you want to be sure it would be added then could tell more about mod functionality, discuss and advertise it a bit to others possibly on ⁠🛰modding / ⁠offtopic or even better on https://github.com/pandorabox-io/in-game/issues and see if you can get agreement from others.

wsor 
thefox6 is still around and is accepting prs i think (so a fork isnt needed just yet) 

The4spaceconstants 
I'm excited for the mod

**Comment by Klaranth** [comment]
The4spaceconstants 
random thing:
what if generators have a set amount of pu and batteries store eu (pu = eu/s)
Exo 
Infinite food, duh.
The4spaceconstants 
exactly
