### ISSUE TITLE
Mod request : Rocket mod   

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#32]
Houlley — 04/25/2021
add the rocket mod
the one with flames that come out from the bottom
it would be a cool way to fly to space and is a tad more realistic

**Comment by Klaranth** [comment]
BuckarooBanzai — 04/25/2021
this had some weird shadow-issues last time i checked that :thinking:

**Comment by OgelGames** [comment]
I assume it's this one: https://forum.minetest.net/viewtopic.php?t=23120

**Comment by Klaranth** [comment]
Yes - 7
No - 7   -- Admin's vote has deciding vote.

<VoteBot@bot> Votes for "Implement Rocket Mod (#32)":
 OgelGames — No
 Klaranth — No
 BuckarooBanzai — No
 marghl — No
 sivarajan — Yes
 xman — Yes
 SolDeNoche — Yes
 PhrogMan — No
 SX — No
 SamWorld — Yes
 Lejo — Yes
 SimonSays — No
 Vamp — Yes
 Eula — Yes
