### ISSUE TITLE
Camera visualisation

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#320]
@OgelGames : I will be adding the digisuff:camera visualization at some point, but i think it might be best to make a library mod for the visualization code, it's a lot of code to be duplicating everywhere ;)
Also there are other mods that could use it, like the jumpdrive and other detecting nodes

@S-S-X : Library for that thing sounds like a very good idea 👍
If made fancy enough then library could even allow displaying things based on per player configuration. I mean it is technically possible. But I'd say it would first be best to just give two options: everyone or private markers / grids / other similar visuals.
Unique default marker colors based on calling mod name. I guess in some situations that could yield interesting special effects as long as mt current mod name is buggy :)

Huhhila : Well JDs could utilize particle-visualization as-is only for the punching case... simulation use case can have multiple players involved, viewing both source and destination at same time.

**Comment by OgelGames** [comment]
Oh right, I meant to do that, now that `vizlib` exists.

**Comment by Klaranth** [comment]
Does this mean, #317 can close?

**Comment by SwissalpS** [comment]
almost, hasn't been implemented in camera yet

**Comment by OgelGames** [comment]
> Does this mean, #317 can close?

No, that's a completely different issue, one that should be on the vizlib repo, but I can't transfer it :/

**Comment by Klaranth** [comment]
Huhhila 
[in-game#320]: Should such visualization be activated by empty-hand punch, digiline message contents or both? Could add visualize arg to search_for_players() and have it draw blue area for spot.y -1..-10, green cube-or-sphere for the found non-air and red sphere at chosen radius around it.
