### ISSUE TITLE
Selling to admin shop via tube 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#323]
chuche952
I wish there would be ability to sell to admin via pipe... :) Even at limited amount per day.

The4spaceconstants 
chuche952: AKA be able to induce transactions by tube.

chuche952
Well, it can be technically implemented through ability to GET sender from teleporttube and then attached to admin shop.

SX 
Auto selling to admin imo does not make really sense and would basically be just unfair lag machine to give out more free stuff for player who already have too much free stuff. Limits however sounds good but I guess some people would start selling through many alt accounts. I mean limits + only manual selling.

chuche952
But would save running on foot, I think it would be nice. Limit with XP and per day if you wish.
Do 1million xp limit

SX 
Yes, allowing only low xp players to sell would also be nice but still prob would cause alt accounts for selling

chuche952
No. I mean, only players with 1mio xp+daily limit like 100k(?) would be able to.

SX 
If it would be high xp limit it would still be just unfair lag machine.
And takes a lot away from poor while giving to rich.

chuche952
How so? It only saves 20 minutes of life time running on foot to admin shop to sell excessive stuff...

SX 
I'm pretty sure there's too many problems with this idea but I guess more opinions and reasoning needed, prob good to move this to github soon. It makes high xp players to run, those who already have free stuff more than what they need. That balances admin shops a bit, it is more beneficial for player who do not have that much yet. That's what is important in my first impression but I think this might not be so straightforward...

chuche952
But why do we have technic and digtron machines then. Essentially you need to collect lots of resources by hand to expand in this area, lots of thinking, and experimenting, but in end it allows to collect in near-automatic mode as a payoff to all that previous time spent.
Plus low level players dont physically collect 10k+ amounts to sell, so automation makes no sense for them

SX 
I do not think that already being superior will be a good reason to increase gap even further.
Also some low level players have been selling what they mine with pick axe, this can even be seen in public chat logs.

chuche952
I don't see how I am superior having own collecting and processing machines and own lua library... the only way I am superior is that instead of swinging an axe, I swing a text editor...

SX 
Low level players simply cannot do that because they do not yet have resources for any automation and that's what increases gap most. Additionally long running gap will increase too through simply just increasing income of current mid / high tier players.

chuche952
I just want ability to sell some limited amounts of ore to admin in automated fashion, to save a dozen runs to spawn and back to exchange few K of excessive ore to buy rare ore like silver mithril. Not taking away existing functionality..
Ok, I pay 100k aka all I have, if this idea gets implemented to the one who implements it :)

SX 
Functionality probably can be implemented in game so if you have proposal you could build it and even test it with admin privs on test server. That however wont guarantee that it'll be added but could allow actually trying / seeing how it would work.

Klaranth 
Actually, been asking for this functionality for a while now.  What could balance things for lower level players is that : 
1 ) Prices for selling through a tube to admin will be 15% lower, so it will benefit people walking into admin shop, or ... 
2 ) A portion (say ten percent) of what a player sends to admin doesn't get sold to admin, but gets redirected to Ecoport, so lower level players will benefit that way.

**Comment by SwissalpS** [comment]
I'm against this. SX has pointed out many good reasons not to do this.
I agree it would be fun, but only for lazy rich players who don't need neither the cash nor the ores, just send via tp-tube to a trashcan :D

**Comment by Klaranth** [comment]
s/trashcan/Ecoport/

**Comment by OgelGames** [comment]
> but only for lazy rich players who don't need neither the cash nor the ores, just send via tp-tube to a trashcan

Agreed, the only players that would need this are the players that don't need this :)

**Comment by Klaranth** [comment]
wf13
Idea: setup a TP tube to each of the admin shops to deposit items, I will think of a way to get money to each person without mistakes.

SX 
There's been some discussion around this idea before, see for example https://github.com/pandorabox-io/in-game/issues/323
Quoting OgelGames: "the only players that would need this are the players that don't need this"

wf13 
I need it and I NEED IT! lol this is not true: "Quoting OgelGames: "the only players that would need this are the players that don't need this"" 

SX 
No, you don't need it. You just want it so bad that you think you need it.
wf13 
kidding I do
I have over 200k sulfur I need gone and sold lol
and that is over 200k MG

**Comment by MCLV-pandorabox** [comment]
sorry wf13. looks like you are just going to have to do a lot of teleporting back and forth with a full inventory like the rest of us.

You could set up a ccompass or a mission block to the admin shop to make it a bit easier, but it's just going to take a bit of effort. But that's what makes it a game, right? Having to put some effort into the things you want to achieve?
Could be worse tho, imagine what it would be like without teleportation.

Other solution; Out source it to some other player for a cut of the proceeds.

Now can we close this issue? because it's not ever going to happen on Pandorabox, or am I the only one that this is obvious to ;P

**Comment by SwissalpS** [comment]
> Now can we close this issue?

It was closed over a year ago :D
