### ISSUE TITLE
 Specific moderator_armor support for otp mod

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#324]
Huhhila
Specific moderator_armor support for otp mod could be nice. Well, haven't really checked how vulnerable the in-game character is before otp entry...

SX 
WDYM, how exactly should otp affect moderator_armor?
Actually I think I'm more curious about why. I mean what exactly is the problem you're attempting to solve?

Huhhila
Worn moderator armor disappears when privs are temp-revoked.

SX 
I guess it is checking players with single globalstep prob? Could change that to per player timer which allows delay before checks, basically it is same as globalstep but just with minetest.after timer instead of straight globalstep. Also allows spreading workload so that for example just single player is checked each ten seconds instead of all at once each few minutes. If it is not using loop like that then prob not this. But short delay anyway, if it takes too long to supply otp response then removal is what should happen and is correct action.

Huhhila
Could also have moderator-armor query otp's mod-storage... but would that need changes in both mods? (In the slow-path where candidate-for-removal armor has been spotted.) 
Well, on the other hand you can think of the current behavior as a hidden security feature: If somebody logs on with your password (without providing otp), on next login you won't get notification about the mod armor getting removed. 
But does the use case for needing such info even exist?

SX 
For generic protection could actually make player invulnerable and locked in place until second factor is provided.

**Comment by OgelGames** [comment]
Closing in favor of the upstream issue.
