### ISSUE TITLE
Block exchange

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#326]
The4spaceconstants
Can't there be different privs for blockexchange_load and blockexchange_save?

BuckarooBanzai
blockexchange_load == worldedit / blockexchange_save isn't harmful ingame

The4spaceconstants 
Simply attempting to log in to save requires privs

**Comment by OgelGames** [comment]
Looks like this already exists, it's the `blockexchange_protected_upload` priv: https://github.com/blockexchange/blockexchange/tree/master#privileges

I think this would be safe enough to be an XP-granted priv, maybe granted at the same time as `areas_protect`?

@BuckarooBanzay your thoughts?

**Comment by SwissalpS** [comment]
what about a bit later with higher tier areas protect priv?

**Comment by BuckarooBanzay** [comment]
> @BuckarooBanzay your thoughts?

Wow, somehow i thought i already added this :facepalm: 

Anyway, i added this now at 15'000 xp: https://github.com/pandorabox-io/pandorabox_custom/commit/e5954393e94e3db0b945f753162104e236ed27e0 (a bit later than the `areas_protect` priv but should be soon enough)

@The4codeblocks fyi ^

**Comment by Klaranth** [comment]
Huhhila
add variants of /bx_pos1 and 2 which make it easier to export non-mapgen'd mapblocks (for debugging snapshots of before/after mapgen state)
SX
I guess for just debugging on test server you could also directly do blockexchange.set_pos(1, "Huhhila", {x=1,y=2,z=3}) and blockexchange.set_pos(2, "Huhhila", {x=10,y=20,z=30})

**Comment by BuckarooBanzay** [comment]
> Huhhila
add variants of /bx_pos1 and 2 which make it easier to export non-mapgen'd mapblocks (for debugging snapshots of before/after mapgen state)

https://github.com/blockexchange/blockexchange/commit/78b5f3c4dfd6ba644edcb6f91b6ab26044e0010f

**Comment by Klaranth** [comment]
Huhhila
Add pandorabox-otp+tan support to blockexchange (alternatively independent otp support for blockexchange local accounts could be simpler)
We already have /wiki_tan (no otp support, just the tan) and /mtui_tan (can use both tan + otp). No similar ways to login to https://blockexchange.minetest.ch/ yet, nor does the local account method there have any otp support (see /help or otp/readme.md if not familiar with it already).
(existence of /bx_login might make any additional command somewhat confusing unless documented properly; as usual it is bit tricky to get UX of security related commands good...)
