### ISSUE TITLE
Mod in progress - Random ores 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#329]
Player1234 
Totally not self promotion... tbh it would be fun though 😛 
https://content.minetest.net/packages/pl608/random_cool/
  
Adds random ores on lava cool

Terrible name though. It doesn't add any ores it just makes it more than just stone. Apparently its also "over-productive"... wonder if that means to many ores?

SX 
At first glance yeah it seems like it would be way too much free ores.

CadViper 
Yeah, I think people would have great big lava farms and be crazy rich in a few afk minutes.

SX 
I'd suggest adding configuration for how likely it would be to get ore.
Maybe even for each different ore type but that would probably mean restructuring most of it.
But... even then not sure if it would be good because it would probably also cause some clogging and other issues with current cobble / stone / sand / etc. lava/water based generators.

I guess having configuration would probably make it more attractive overall anyway.

The4spaceconstants 
Imagine a grinder with a chance of ore dust.....

Player1234 
oke ill work on it...

MCLV 
Such a grinder would be a malfunctioning one in my book. Also makes machines unreliable and will throw my already wonky Math skills completely off :)
I can accept 'nature' to be unreliable. But machines... They should just work, or be scrapped

SX 
I guess that was an attempt to say that getting random ores from cobble gen would be very similar to a grinder that would every now and then spawn random ore.

The4spaceconstants 
Half an ore*

Klaranth: Basically, implementing a sieve?

**Comment by OgelGames** [comment]
Not suitable for pandorabox. Even if it required a convoluted process the clever players on pandorabox would find a way to automate it.
