### ISSUE TITLE
Fixing Oririgi recipe.

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#330]
chuche952
Oririgi recipe is currently broken.

**Comment by OgelGames** [comment]
Problem there is that we currently don't have any item that is `group:food_seaweed`.

**Comment by SwissalpS** [comment]
we could add that group to the existing seaweed in pandorabox_custom

**Comment by BuckarooBanzay** [comment]
thanks @OgelGames :heart:
