### ISSUE TITLE
End of World antics 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#334]
CadViper 
When you reach the end of the world, when you enter the void it teleports you to the other side of the map.

BuckarooBanzai 
Possible, this will get weird though with the existing buildings on the world edge 🙃

Huhhila
Consider having outside the world drop protections like warzone does.

**Comment by OgelGames** [comment]
Maybe an idea for my silly mod, I think it would be a bit too weird for normal gameplay.

**Comment by Klaranth** [comment]
Or something for Halloween?

**Comment by Klaranth** [comment]
Added Cadviper's idea to Silly thread, closing this one.

**Comment by OgelGames** [comment]
Turns out there's already a mod for this: https://content.minetest.net/packages/Don/worldedge/
