### ISSUE TITLE
New Weapons

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#336]
ProbMaxino's_twin 
Pistols maybe ?

**Comment by OgelGames** [comment]
I think Buckaroo said something about testing [ranged weapons](https://content.minetest.net/packages/davidthecreator/rangedweapons/) ages ago, something about them being buggy or not compatible.

Personally I'd say to keep pandorabox gun-free (cannons are fine though).

**Comment by Klaranth** [comment]
And we have a railgun now ... 

I'm fine with closing this one.
