### ISSUE TITLE
Flowing water buckets (silly mod)

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#337]
The4spaceconstants
Funny idea: "Flowing water" buckets

SX 
So when you place it somewhere it would actually place flowing water which would then just do what flowing water normally does?
I guess that could be used as single use downwards only water elevator for some mining and exploration ops but then there's better methods that work in similar situations. Would there be some other real uses for such thing?

The4spaceconstants
It wasn't meant to be practical anyway, it was just a joke.

SX 
Maybe for Ace's silly mod. Actually it would not even need separate item and could be handled completely with item metadata.

The4spaceconstants 
Same for the different levels of flowing water.

**Comment by OgelGames** [comment]
I'm currently keeping track of silly mod ideas in the "Silly Ideas" thread in discord. This one included.

I probably should copy them over to an issue on github, but for now they are there.
