### ISSUE TITLE
Bag  > < Inventory button

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#339]
Sher Khan 
A button to transfer all the items from the bag to inventory and vice versa

**Comment by Klaranth** [comment]
Huhhila
So basically that silver/gold/mithril chest feature for unified inventory bags too?

**Comment by SwissalpS** [comment]
with the new mouse inventory handling, is this still an issue?

now you can just keep LMB pressed and drag it over all slots to move inventory items really fast.

**Comment by Klaranth** [comment]
> 
I just tried that, doesnt seem to work for me.  Just LMB?

**Comment by SwissalpS** [comment]
you need a relative new build of minetest (from github, repos won't have it yet)

**Comment by OgelGames** [comment]
I agree, with the improvements to inventory management this really isn't a problem anymore.

Also, there isn't much room in the formspec for the buttons, unless you removed or shrunk some stuff.

**Comment by SwissalpS** [comment]
> removed or shrunk some stuff.

which would make things terrible for small screens and most mobile clients
