### ISSUE TITLE
Corona ingots

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#34]
sunks — 04/26/2021
corona ingots?

SX — 04/26/2021
Already wearing hazmat suit all the time :laughing:

**Comment by S-S-X** [comment]
Relates to #33 discussussion, however "corona ingot" would be more related to HV electric arc furnaces suggested for molybdenum ore processing #19.

I'm not sure however if so called "corona treatment" is really used with molybdenum processing but I guess you can call plasma arc furnace smelting corona treatment. Probably still should not call resulting ingots corona ingots.

**Comment by OgelGames** [comment]
Closing this, no benefit to keeping it open, and SX's comment links it to the other issues anyway.
