### ISSUE TITLE
Tape Measure ? 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#340]
Sher Khan 
Can we add this mod? It will help a lot, for counting, measuring, leveling nodes etc.,

https://youtu.be/aaKzqmhgzlo
[Minetest Videos](https://www.youtube.com/channel/UCdiuryhdSBUxQse2rarVqPg)

[Minetest Mod Review: Laser Distance Meter 32](https://www.youtube.com/watch?v=aaKzqmhgzlo)

OgelGames (AceRichman) 
Seems very limited to me, only 32 block range and can only measure sideways, not diagonally or up/down? good idea, bad implementation :P 
Also, that laser seems like a great use for vizlib :)

Sher Khan 
I see, can't we modify the 32 block limit? and for up, we can use another but rotate it with screwdriver? (sorry for asking these questions as if this was simple but, maybe complex to implement. Since I have no sense of minetest engine on how it works neither lua code) 

SX 
With extended range this thing is basically lag machine because it has to do ray tracing server side and must load all blocks until it hits limit or wall.
Well seems this one doesn't do actual tracing but works more like beacons but all the same, it still has to load every block it crosses so extended distance isn't really option for reliable operation. Perhaps extended range if it would be renamed as a "Laser Mapblock Loader" or something.

CadViper 
I think this is a really good idea, But would only be useful if it had like a 400meter distance. But I foresee a lot of issues implementing it.

Sher Khan 
Previously, I used to measure with the compass not the current mod on "pandorabox" but on "yourland" and marking a visible waypoint with just single right click and moving a away to calculate the distance.

SX 
You could abuse tube tool to measure distances as it allows getting waypoints to teleport tube positions, however it wont bring much more than waypoints available through inventory and you have to get creative.
By not much improvement I mean you still have to run around to place markers, basically just removes marker limits (but on the other hand requires tp tubes)

Sher Khan 
How do you get the positions of teleportation tubes? I placed then I right click and left click didn't showed me, even I created two with same name. Are we talking about pipeworks teleportation tubes right?

SX 
you could abuse tube tool
Sneak + left click (on configured tube to get listing for its channel, on something else to get listings for stored channel)

**Comment by Klaranth** [comment]
Jeremy
It could be neat though, if there was some type of cheap way point block, where you could place two down, set them on the same channel, and it would show the distance and qords. perhaps even a line going between
could be a handy replacement for scaffolding.. in which case it could be more expensive, then 

Huhhila
Or as upgrade of mapserver:border or one of the related nodes?

SX 
Upgrading mapserver nodes sound like very good idea, doing that would also bring better UX for existing functionality and could very well solve current request without adding any new tools or nodes.

**Comment by Klaranth** [comment]
SX 
Would probably still be very good to upgrade mapserver nodes, would possibly make those more interesting and make ppl use those more often. But tape measure seems like good solution for just measuring distance anyway even if its functionality overlaps a lot with other stuff.

**Comment by OgelGames** [comment]
Yes, tape measure. https://github.com/OgelGames/tape_measure
