### ISSUE TITLE
Parkour spiral

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#341]
Sher Khan 
Parkour spiral 
https://youtube.com/shorts/9uSj6tjZ8aw?feature=share

Klaranth : 
That is Minecraft, not minetest. But if you need a new project ... build one yourself, add a POI node to it, and a TN box and invite players over ...

**Comment by Klaranth** [comment]
Could easily be a project to build it by one or more players. :)

**Comment by OgelGames** [comment]
Could even be part of a contest, each player building a layer 🤔
