### ISSUE TITLE
2nd level tubes

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#342]
Klaranth 
Combine tube specifics for new level of tubes, e.g. combine Vacuum with Teleport, so all vacuumed up items goes directly to a specific target.

**Comment by OgelGames** [comment]
But you can already do that?

**Comment by Klaranth** [comment]
Checking the craft guide, I can't. I can put two different tubes side by side, but I can't combine them to a next level upgrade that does both in one tube.

**Comment by OgelGames** [comment]
I mean placing them next to each other in the world :D 

Personally I think we should avoid putting too much functionality into a single node, even something like the digibuilder getting a the ability to dig nodes is pushing it.
