### ISSUE TITLE
Upgrade Protector Blocks 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#345]
Similar to being able to rename area protect, make it so protector blocks can be renamed, too.

**Comment by SwissalpS** [comment]
I don't understand, protectors are player/XP/priv related and have their corresponding names. Why would you want to (re)name them?

**Comment by Klaranth** [comment]
I just added it, ask Ace for an answer to that.

**Comment by OgelGames** [comment]
I don't know either ¯\\\_(ツ)\_/¯

**Comment by SwissalpS** [comment]
just more meta cruft, if the idea is to add an area identification in HUD.

the protectors span such a small area, I don't see why bother. If you really want to name a small area, just use areas mod.

**Comment by Klaranth** [comment]
Fine with closing it.
