### ISSUE TITLE
New Discord channel + bridging 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#346]
Sher Khan 
For discord - lua (or programming) channel connection/creation/linking with discord and this server
Because I'm discussing all programming/lua stuff in ⁠offtopic

OgelGames 
yeah, thats been mentioned a few times, its about time it was done 👍 
(not actually sure how the linking works myself, need Buckaroo to do that) 

Sher Khan 
Also #ask-minetest-related channel (for other than programming, in-game related) if possible 

OgelGames 
wouldn't that just be ⁠main?

BuckarooBanzai
We linked "modding" already: https://github.com/pandorabox-io/pandorabox.io/commit/72b76747437f9539b99dbb3cb5da39a811e197a2 is there a benefit for an additional "lua" channel?

add `pandorabox-modding` channel · pandorabox-io/pandorabox.io@72b7...

Sher Khan 
modding not necessarily mean luaC programming, isn't it? yes modding is subset of programming 

OgelGames 
modding is more for dev stuff, #lua would be for luacontoller stuff

BuckarooBanzai
https://github.com/pandorabox-io/pandorabox.io/pull/783 (can't create a "lua" channel in the discord right now due to firewall issues ;)
add `lua` channel by BuckarooBanzay · Pull Request #783 · pandorabo...
bridges the #lua channel from ingame to discord and irc (as discussed in #ideas)
TODO:
create a #lua channel in the discord server

OgelGames 
oh i can do that :)
done, merged the pr too :)
will that work immediately or does something need restarting first? 

BuckarooBanzai
It needed a restart of the "matterbridge" service on the server, i did that manually (i'm behind a corporate firewall right now and need to employ a few "workarounds" to have proper internet/ssh access, it is tedious and i don't like to do that too often...) anyways: the restart/reload thing needs to be automated, doing that another time though

OgelGames 
ah, i though that was it
the part that i couldn't do :)

**Comment by OgelGames** [comment]
*points to `#lua`*
