### ISSUE TITLE
Snow / Ice Bricks

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#35]
sunks — 05/01/2021
snow/ice bricks?
https://github.com/Terumoc/terumisc has at least ice bricks, depends on stuff already on pandora
GitHub
Terumoc/terumisc
A mod for the open-source voxel game Minetest (https://www.minetest.net/) that adds a variety of minor things. - Terumoc/terumisc
ice is criminally underused

wsor — 05/01/2021
Seems bloated for what you want....

sunks — 05/01/2021
maybe, but i figure they could be extracted from it like cherry tree is?
that's if people lust after some more use from ice
seen it going in /dev/null something must be not so right with ice

OgelGames (AceRichman) — 05/02/2021
supply > demand :wink:

**Comment by Klaranth** [comment]
@OgelGames  @S-S-X  
Do we really need ice and snow bricks?  Can this be closed?

**Comment by OgelGames** [comment]
So I got the ice bricks (and other ice nodes) working using the textures from `terumisc`, but I'm wondering where it should be put, I was thinking `pandorabox_custom` would be fine, but I'm not quite sure if the license (GPL-3.0) is compatible? 🤔

**Comment by S-S-X** [comment]
Would some other mod accept it like moreblocks?

**Comment by OgelGames** [comment]
That would have the same problem, I was thinking maybe put it in a separate mod like was done with redwood: https://github.com/mt-mods/redwood

**Comment by OgelGames** [comment]
https://github.com/mt-mods/ice

**Comment by BuckarooBanzay** [comment]
they _do_ look nice :+1: now i have a use for all my collected snow (after i compressed it :X)
