### ISSUE TITLE
Bug on planting some crops.

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#361]
chuche952
planting crops seems to be bugged a bit: seeds continue lying on soil now before going into plant form, which is okay. But converting into plant takes a lot of time AND player present near it.

Huhhila
I don't see any difference to how they have been working for years. Or do you mean they no longer "catch-up" that player-absent-for-a-while part?

chuche952
there is huge difference now, or is it only for hemp crop? Eitherway, seed doesnt go into soil immediately now, but after 2 minutes standing next to it.

so Huhhila confirmed the issue, at least with hemp crop. Not sure if others are affected.

Huhhila
so... does this change look like what you were speaking about? https://github.com/minetest-mirrors/farming/commit/2446f3d76c948df37b101433f66a3d8567c66405
use farming seed placer function · minetest-mirrors/farming@2446f3d

chuche952
seems like this. It now changes cell into seed instead of crop, which no other seed is doing, including vanilla seeds. And since they only grow in plant form, it could result in seeds laying around until moving into plant stage.
Wait, vanilla is also doing same now.
Wheat is now also seed object before turning into plant (at random rate?).
There is no vanilla farming, they all belong to "farming"
Cucumber doesnt do this.
Ok ok, this is exactly that change, exactly those plants are broken, all other plant normally. Tested with cucumber, tomato, corn, salad.
This isnt digtron specific, planting by hand has same problem with these 4 crops.

This is very seriously broken. Its not 2 minutes, it can be up to 5 minutes easily.

AceRichman
looks like it's this commit: https://github.com/minetest-mirrors/farming/commit/b5f71d80255c8f6e73f9b7d5bc34c1b93368d09d
check for old wheat/cotton seeds and grow to stage_1 via abm · mine...
not sure exactly what it does or why

chuche952
So big changes currently slipped into farming. Seed-based plants now explicitly need Mulch to reliably kick into plant form. Digtrons would need an extra mulch pass. Without mulching, the seed needs both player and some time and some randomness.

Ok, Tenplus1 answered. He wants people waiting next to plants for real-life 5 minutes. This is sweet. I wont push the discussion further for obvious reason of making whole even harder than currently is.

The4spaceconstants — 09/03/2023 11:37 AM
Confused about the digtron part, could you elaborate?

chuche952
If you use farming digtron, field will require mulch over seeds application pass (digtron builder module).

AceRichman
I'm pretty sure we can override the changes to revert them, we've done that for a few things from farming
seeds IRL don't need people around them to germinate, so why should that be the case in minetest

chuche952
Technically, this boosts the need for fertilizer to produce four plants: cotton, hemp, wheat, barney. Two of these are used in recipes. The logic TenPlus1 mentions is to increase difficulty if mass-producing them. This isnt actually anything hard to overcome, but will somehow increase difficulty for beginners. YMMV.

The link to the commit can be found at notabug, Tenplus1, farming, inside the last closed ticket. Its same one that Huhhila has provided.

chuche952
Ok, its impossible to use all types of fertilizer through digtron. So all four seed crops are not viable to be grown via digtron in large quantities.

yes, this farming change probably should be reverted. A lot of crops are affected by this. And tomato, cucumber, soy.. do not have seeds, but do have in real life. So this germination phase is very very weird.

The4spaceconstants 
And also the fact that Tenplus1 wanted this added for a difficulty increase.

**Comment by OgelGames** [comment]
As far as I know, this issue was fixed by this commit: https://codeberg.org/tenplus1/farming/commit/fd205e10fc38a121cefb23d63a7f5b14aa504507
