### ISSUE TITLE
Temporal XP multiplier 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#363]
Sher Khan 
Idea: XP multiplier effect for temporary for few minutes

An item that is very hard to make or hard to find, and consuming it, will give that player a temporarily boost in XP generation for a short period of time.

SX 
Like consume xenomorph egg to gain some 10x to 100x multiplier for half minute  or so, could work but not sure it is worth the trouble in the end. But doing that could actually make trading xeno eggs more worthwhile and through that actually be overall very good and relatively simple addition.
And full automation also wouldn't be too easy so fully automated XP farming probably wouldn't be issue at all.

**Comment by S-S-X** [comment]
* Very related: #194 and a list of issues linked there.

**Comment by OgelGames** [comment]
It's impossible to balance such an item, if you make it easy to obtain then it will be overused and abused, and if you make it hard to obtain then the players that actually need the XP won't be able to use it enough.

Regardless, I think this is a bad idea, and it's basically just another way of saying "make XP easier".

**Comment by S-S-X** [comment]
> It's impossible to balance such an item

That's not exactly true. Balancing just has to be done in a way that it actually wont make XP any easier, more important not any faster.

Basically, if balanced well, it would be additional content and alternate way to do things in game but would not give any real benefits to anyone.

It is hard to balance such item but far from impossible.

**Comment by Klaranth** [comment]
et 
idea: xp items
you obtain xp items by sacreficing your own xp
if you use/eat them, you gain the xp

how this would impact gameplay
this would make you able to donate and sell xp
this could reduce xp farming a lot
 
Kermit 
I must say that I never xp farmed and I doubt I saw anybody doing that.

et 
Well, birdlover32767 is.

SX 
I think would be better to have alternative ways to gain similar amounts of xp through playing instead of trading or transferring it, preferably something that would actually be useful in game or something that would bump up players real pandorabox/minetest experience.

**Comment by Klaranth** [comment]
et 
maybe achievements would be a good idea 

The4spaceconstants 
yes I am a 12/10 supporter of this

**Comment by SwissalpS** [comment]
> this would make you able to donate and sell xp
> this could reduce xp farming a lot

It would not stop XP-farming at all, just defer it to the players that sell it.
