### ISSUE TITLE
Night vision goggles 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#364]
stephen
Night vision goggles.... would make building in the dark cooler.

Klaranth
There is a very old mod (from 2013), mostly in dire need to rewrite :
https://forum.minetest.net/viewtopic.php?t=4277

**Comment by Niklp09** [comment]
You could use parts of my night vision goggle glas implemenation (based on illumination and titanium). https://github.com/Archtec-io/titanium

**Comment by OgelGames** [comment]
I think this is asking for something different from what `illumination` does, probably more like Minecraft's night vision effect.

It could be possible to simulate such an effect using [`player:override_day_night_ratio()`](https://github.com/minetest/minetest/blob/a98200bb4c1edb2c982577fb01b30075665ab488/doc/lua_api.md?plain=1#L7974-L7977) and swapping the night and day skyboxes, but that would only work where there is natural light, so it would do nothing underground or inside a building.

**Comment by Klaranth** [comment]
Since we have a miner's helmet lamp already, can't we make it a version 2 to that lamp? Much similar to mapkit+radar?

**Comment by SwissalpS** [comment]
the binoculars seem a better fit for an mk2 than the helmet lamp. But user may not like having to 'zoom' OP probably expected the vision to be permanant -> goggles

**Comment by Klaranth** [comment]
I don't like the idea of permanent night vision.  Cause in bright daylight that would blind players.

**Comment by S-S-X** [comment]
> I don't like the idea of permanent night vision. Cause in bright daylight that would blind players.

Permanent here (assuming SwissalpS's reply) means permanent as long as player chooses to have it enabled.
As in you do not have to hold down a key or do actively something else to keep night vision on but ability to turn it on permanently until you turn it off (take it off, do something to disable it). Like a traditional light switch.

**Comment by Klaranth** [comment]
wsor 
easy enough to override the players time of day to day time (player:override_day_night_ratio) and throw a full screen hud like a vinette or something around the edges when you have the googles on
Jeremy 
Not something i could do but definitely a cool idea.. I wonder if it's possible to make it so everything you see is also only grayscaled, (like night vision).
wsor 
iirc hud supports transparency, so could throw a semi transparent grey image up to sorta greyscale things
Sher Khan 
Night goggles feature is already present in Tunneler's Abyss Server.
Though you have to earn in-game money to buy that item. I already have them. Also they have night vision goggles which costs more, which you can use inside caves where sunlight doesn't reach
Jeremy 
Oh neat! I wonder which mods implements that
I check on tunnelers abyss.. it seems the mod which adds them is called "elements" and is closed source :/
The4spaceconstants 
is "elements" owned by tunneler's abyss
frog 
probably
The4spaceconstants 
the mod is very simple, someone can just remake it (hopefully)
