### ISSUE TITLE
Limit inventory guide to what players are ranked for to use 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#37]
wsor — 05/14/2021
Suggestion, if ranking stuff, ability to hide it from inventory till you are that rank

SX — 05/15/2021
I think effect wsor is looking for would be like one old topic: "Require n amount of XP to wear lava gear". So it would hide those items, also railways, trains etc. that already require XP?

wsor — 05/15/2021
If the user is not allowed to use it, it should not be in there specific inventory
This could easily be acomplished via a group check in unified inventory
Likeif  item has group x and user has _priv, show it

**Comment by FeXoR-o-Illuria** [comment]
The crafting guide is most needed for new players. Those usually also have less XP. So don't hide information from those who needs them most, even if they can't use it.
It's helpful for planning and checking out if one wants to play on a server in the first place.

**Comment by SwissalpS** [comment]
I don't like this idea at all. How would I have noticed that an rtc can be crafted? Not many can be found in world.

So a solution would have to involve user toggle to switch between 'what does server offer' and 'what can I use'.

Seems to make UI complicated without actually adding anything to the game.

**Comment by Klaranth** [comment]
Low or non-existing chance of being implemented. Closing issue.
