### ISSUE TITLE
Skip Bedtime 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#374]
Marsufoman
Add a command block/vote to skip night.

Alliecakes 
settime priv

Marsufoman
Who would get it though

Hedgehog
A vote to skip night we already have : those that want the night to skip, go to bed. 2/3 of players are asleep .... presto daytime 

Marsufoman
Theres basically always someone who wont

Hedgehog
Hence 2/3 majority. Six players can have two who dont want to

Marsufoman
Not 2/3, when it's for example, 8/9

Alliecakes 
game should require u to write command if u want to be included in voting for daytime via bed
many people are to extent ignorant to players asking others to goto bed or not

Hedgehog
heroo7082 : go, write it :)

Alliecakes 
its simple write /pstv = partake settime voting this session
if u don't that session, your bed is ignored

**Comment by SwissalpS** [comment]
If ppl were actually getting 2/3 to go to bed, I would want to raise that to 80-90% of all players.
By the time sufficient players are in bed, it is daytime already anyway. Same is bound to happen with a chat-based voting system.

**Comment by Klaranth** [comment]
The night is often a good moment to craft while you mine and build during the day. It isn't like you have to sleep to keep playing. 

Which would be an interesting side idea for this. What if sleep is set up much like food?
