### ISSUE TITLE
Add Logistica 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#392]
wf13 
add Logistica https://content.minetest.net/packages/ZenonSeth/logistica/
On-demand item transportation + Powerful Storage
frog 
that is a/includes item transportation mod, we have pipeworks (pipeworks is a huge mess but like i dont think its a good idea to add a mod that heavily competetes with it) 
i think pipeworks should be improved but i have no idea how
it looks ugly, there is a visual glitch with backface culling, if that gets fixed the tubes will look kinda messy, liquid transportation is basically useless, something needs to be compatible with pipeworks for injectors to be able to use it (instead of just being able to pull/push from an inventory without the mod even knowing about pipeworks)
and also the autocrafters feel like crap to use 
and also the tech mods arround it aren't really comparable to techage besides mesecons, digilines, mt-mods/digistuff, that's like really good 
oh and also yeah pipeworks uses entities, lag isn't a big issue on pandorabox, which i am like 50% sure is an insanely beefy server considering that buckaroo literally provides minetest server hosting but the issue is them despawning, at least test_user told me that he had a horrible experience with it 
The4spaceconstants 
injectors requiring support just made me feel like a fuse blew inside of me
wf13 
its much better for storage and the "pipes" cost alot more to make, so it should be added
frog 
why not just remake the storage part of it to fit pipeworks
wf13 
Logistica is already awesome
frog 
i havent used logistica can you tell me more about it
wf13 
pipeworks is for simple use
its a storage mod
Logistica is complicated to use and to make
frog 
why would someone use it then, to make slightly more compact machines
wf13 
but has HUGE advantages over pipeworks
https://www.youtube.com/watch?v=tx3YbpxHEdM
You can store items and blocks in mass (like drawers but ultra smart)
frog 
ok so like its pipeworks and lwcomponents storage indexer bundled into one mod
(lwcomponents storage indexer is basically that, with digilines and pipeworks support)
disclaimer: i watched like 26 seconds of the video
wf13 
its much better why not add it?
frog 
balance probably?
wf13
because of what it is
frog 
from the first 26 seconds of the video - let me guess its a thing that combines chests and lets you search thru them
if so then yeah that literally makes drawers kinda obsolete, i mean they would still have use, just not as huge nvm
wf13 
it has only space for about 5k items upgraded and drawers have much more without upgrades lol
its quite good. it needs to be added. it would help so much
frog 
oh so its like a chest setup(?)
what else does the mod have
wf13 
item transport but nothing I would use and random item storage, crafters and the "filters/injectors" that mesecons has
and much more
oh liquid storage that is very nice and cobble generation

**Comment by SwissalpS** [comment]
\<insert link to duplicate request with other mod doing mostly the same and was rejected\>

**Comment by OgelGames** [comment]
Yeah, that mod would make item storage too easy. Definitely not adding that mod.
