### ISSUE TITLE
A street has been built too close to my ship, preventing me from moving it.

### ISSUE THREAD

**Issue by TangentFoxy** [pandorabox-io/in-game#403]
I am trying to jump a ship from `4974, 14, -975` to `4935, 30, -930`, but it presents the following error when I try:

```
This area is protected with priv 'protect_streets'!
Jump-source is protected!
```

I was extra-confused because my ship is protected, and everywhere around it doesn't show an Area.

![image](https://github.com/user-attachments/assets/784ace53-860f-4347-adec-0564bd0e5758)

It looks like the street that was built while I was away for a couple years has a protection block too close for me to be able to jump away:

![image](https://github.com/user-attachments/assets/ac9105a3-4889-478b-844e-375e47a8db87)

If for any reason the area I intended to go to is unavailable when an admin sees this, please at least jump my ship somewhere I can move it from afterwards, preferably not too far away.

**Comment by SwissalpS** [comment]
This can happen :D will be solved soon. Protector (incl. priv protector) blocks can be placed so they overlap an area protection without giving a warning. I don't think there were bad intentions here.

**Comment by SwissalpS** [comment]
I now see you have only got 226'045 XP so you wouldn't be able to move anyway. (Assuming your in-game name is Tangent)

**Comment by SwissalpS** [comment]
I went to have a look, looks like an admin already moved your ship as requested ;)

**Comment by TangentFoxy** [comment]
> I don't think there were bad intentions here.

Oh yea, I'm certain it was not intentional.

> I now see you have only got 226'045 XP so you wouldn't be able to move anyway.

Huh? Why? Since when? Did permissions unlocking change at some point? I was able to move things around here no problem. It was just that one protector accidentally overlapping. I have another couple ships I've moved around and below ground even.. I think I've taken my shuttle to space too.

(And yes, that is the correct username.)

---

And thank you to whoever moved it for me, I appreciate it very much!

**Comment by SwissalpS** [comment]
> Huh? Why? Since when?

https://github.com/pandorabox-io/pandorabox_custom/blob/1a2c8c4635508eee542465ce1b620b20c5071064/travel/jumpdrive.lua#L16-22

Anyone can jump around lower than -20y and higher up than 100y, since almost forever.
But for that sliver between you need 450k XP

https://github.com/pandorabox-io/pandorabox_custom/blob/1a2c8c4635508eee542465ce1b620b20c5071064/xp_priv.lua#L18

**Comment by TangentFoxy** [comment]
Someone must've manually given me the permission at some point then, because I haven't been restricted by this. I thought the permission unlocked lower as a result. Thank you for the explanation and linking to where all privs are defined!

**Comment by SwissalpS** [comment]
> to where all privs are defined!

Not all are defined there, just some Pandorabox XP-related ones.
