### ISSUE TITLE
Minigame - Black Jack

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#42]
Houlley — 06/19/2020
blackjack
but not using in-game currency

Houlley — 06/22/2020
Maybe rate on number of wins; also it’s generally short in case people want to go back mining building etc

**Comment by Klaranth** [comment]
Not sure how a blackjack minigame could be created, but, ....

VanessaE created a Slot Machine mod:
https://forum.minetest.net/viewtopic.php?t=20790 

Yes, it uses MineGeld, and according to that page, is fully customizable. 

> The hope is that others will take this and run with it, perhaps fine-tuning the example machines or using them and the graphics work files to create more machines, either as new machines to be included in the modpack, or as external mods/modpacks.

**Comment by Omikhleia** [comment]
Slot machines "as a mod" are very specific... Typically, black jack would be doable in-game with the current nodes, no? Sure, a bit of lua coding, but I don't think its not doable.

**Comment by S-S-X** [comment]
Sure you can build it with lua controller paired either with touch screen or some other lcd screens. Only thing not currently available is textures for cards but I think even these could be done well enough with some creative combination of available textures and some text.
LCD wont allow textures but with some additional work it should be possible to create something similar to https://github.com/jezman/blackjack

**Comment by Klaranth** [comment]
et 
As if it wasn't already. I mean, the minegeld is basically worthless, because you can get stupendous amounts of ores from boring dimensions.
The4spaceconstants 
Minegeld is basically worthless, but it's statically worthless.
and minegeld isn't ACTUALLY worthless, because non-renewability or unreliable-renewability
et 
The admin shop: You can get iron lump from hairballs. Wait. Isnt the entire reason minegeld is worthless because of the admin shop

**Comment by The4codeblocks** [comment]
> Only thing not currently available is textures for cards

well we have (currently, dunno about the past) `[png:<base64>`
unless you mean in-world displays instead of touchscreens
