### ISSUE TITLE
Transliteration

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#43]
SX — 07/06/2020
for pandorabot: https://discord.com/channels/513329453741637637/668090931861258250/729456054001467443

BuckarooBanzai — 07/06/2020
i tried the nodejs variant (https://www.npmjs.com/package/transliteration) but it does not work with some utf8 characters :/
console.log(transliteration.transliterate('𝒟𝒶𝓃𝒹𝑒')); just prints out "" :stuck_out_tongue:

SX — 07/06/2020
well, I tried that lua transliterator oob: print(t:transliteration_get('𝒟𝒶𝓃𝒹𝑒')) and that printed me??me??me??me??me?? to console.

SX — 07/06/2020
lists seems to be specialized and pretty short for most transliteration projects around web but probably someone has combined that stuff already... maybe.. just cant find it.. or it does not exist.

SX — 07/06/2020
seems like at least google knows how to transliterate those

**Comment by S-S-X** [comment]
Somewhat related while not exactly same thing: https://github.com/minetest-beerchat/beerchat/issues/38
Also this (similar to above): https://github.com/minetest-beerchat/beerchat_proxy/issues/39
And this: https://github.com/minetest-beerchat/beerchat_proxy/issues/16

**Comment by S-S-X** [comment]
This would probably be better moved to beerchat_proxy mod as new issue and closed here?

**Comment by OgelGames** [comment]
> This would probably be better moved to beerchat_proxy mod as new issue and closed here?

I'd say yes, it's more on the technical/behind the scenes side of things, so doesn't really fit here.

**Comment by Klaranth** [comment]
@S-S-X  @OgelGames  
Can one of you please arrange the move to beerchat_proxy mod and close this issue?  Preferably today ( May 28 2021)
Thank you. 

Or tell me if and how I can do that.  :)

**Comment by Klaranth** [comment]
> > This would probably be better moved to beerchat_proxy mod as new issue and closed here?
> 
> I'd say yes, it's more on the technical/behind-the-scenes side of things, so doesn't really fit here.

Copied as requested.  
Closing this.
