### ISSUE TITLE
Disease server event 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#47]
Oh this does not even have any recorded issues and probably mostly discussed using private messages: https://docs.google.com/document/d/1LYgVzQ59vZP6_ccREFqvlHuZDNhELAxEanB-JHucUjw/edit?usp=sharing
Google Docs

Disease simulation for Minetest
Recently, @S-S-X mentioned an idea of modeling disease spread in-game. It can be done several ways and I see a potential for a large-scale in-game event there, so I'm documenting ideas I've been discussing with @S-S-X and @SwissalpS. The minimal way may be similar to [Technic mod](https://github...

**Comment by Klaranth** [comment]
The really simplest way would be player to player infection. Like when you visit spawn or the tutorials, or the shops.  

With the shops, you could get infected when the shop has been used prior to you by an already infected player. 

Most things that want to kill humans, don't really survive any vacuum. So, infected players can move into space, and flush the air out of their ship, killing it.  

No idea if you can also use the template of this for a zombie apocalypse around Halloween ....

**Comment by Klaranth** [comment]
Huhhila: 
Limit the effects to warzone and above or similar. 
(For disease that doesn't happen to be capable of surviving on earth, which would be more newbie-friendly approach)
(or one that goes to hibernation mode when exposed to earth... extraterrestrial diseases can be applied quite liberal amounts of scifi since pretty much nothing is known about such anyway)

**Comment by SwissalpS** [comment]
This idea was discussed before current pandemic and stopped abrubtly because of it. Let's keep it that way. Too real atm.
