### ISSUE TITLE
Allow larger item stacks for high XP players

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#5]
As minegeld can stack to very high amounts, at 750K XP everything can be stacked to 9999 items ?

Comment from 1hit  :
max size of item stack is part of the item's registration.  Modulating that per-player is non-trivial.

**Comment by Klaranth** [comment]
SX: 
Stack sizes if done some weird way will be broken anyway, there's not 100% control but you can get oversized stacks. I think not good even if it could be done completely. Good example is smelting mese block with lava pick.

**Comment by BuckarooBanzay** [comment]
One ~~hack~~solution for dynamic stack size would be a new kind of item with a large stack-size that serves as a "holder" item for others, the containing item could be stored in the metdata somehow.

Still not trivial but one way i guess :P

**Comment by OgelGames** [comment]
Or just make wrenches craftable...

**Comment by OgelGames** [comment]
Closing this due to it being impractical (or potentially impossible) to implement.

> Comment from 1hit :
max size of item stack is part of the item's registration. Modulating that per-player is non-trivial.

**Comment by Klaranth** [comment]
> Or just make wrenches craftable...

As this is now a fact: 

Huhhila
wrench mk2 with an inventory slot which eats diamond blocks for extra range, 1 per extra node distance or so? :)

**Comment by OgelGames** [comment]
Wrenches are overpowered enough, and you can also just walk closer :P

Also this issue is unrelated to that suggestion, so I'm closing it. Open another issue if necessary.

**Comment by Klaranth** [comment]
wf13
change the stack size to 100
et 
YES i would love this (even if it's gonna break some code, i mean whatever) 
FeXoR
I'd definitely prefer 60 (divisible by 2, 3, 4, 5, 6 and 10, 12 and 15 as a bonus) or 64 (power of 2). 100 is only divisible by 2, 5, 10, 20, 50. 99 is even worse though and only divisible by 3, 9 and 11. But it's at least the largest 2 digit number in that strangely chosen base 10 system.
The crafting grid gas 9 slots and from those stack sizes that came up only 99 is divisible by 9. So probably not that bad of a choice (Though I think using all crafting grid slots with the same material mostly shows the lack of creativity in craft pickets :p)
The4spaceconstants 
or 120
FeXoR
Yea. 99 has the advantage of being devisible by 9 though - many recipes use 9 of something like ingots to blocks, shards to crystals and compression.
wf13 
though 100 is very nice and even
The4spaceconstants 
but still a garbage number to use
wf13 
why?
it evens things out immensely
The4spaceconstants 
/1 /2 /4 /5 /10 /25 /100
compared to 120: /1 /2 /3 /4 /5 /6 /8 /10 /12 /15 /20 /24 /30 /40 /60 /120
the only things 100 has that 120 doesn't is 25 and 100, and when did you find the need to divide by either?
wf13 
many times  with technic and default
The4spaceconstants 
tell me how
wf13 
with all types of wood
100 with mese for JD backbones  (IK not technic)
for technic smelting the latex from rubber tree farms (bc 100 latex irrc + 50 coal dust = 100 rubber)
and many more
plus it wont change the price per stack much, if at all
and is a clean rounded number
MCLV
why not go for a lower max stacksize like 60. it can be devided by a lot more :)
wf13 
Blockhead> https://en.wikipedia.org/wiki/Highly_composite_number
A highly composite number is a positive integer with more divisors than any smaller positive integer has. A related concept is that of a largely composite number, a positive integer which has at least as many divisors as any smaller positive integer. The name can be somewhat misleading, as the first two highly composite numbers (1 and 2) are not...
How about 96?
wf13 
keep it at 99 then
we want a higher number, even if it just adds 1 block to the stack
I get where you come from but that would decrease the value of the stack
et 
ok i get why 100 might not be the most practical number but like.... 99 is just ugly imo
The4spaceconstants 
@MCLV (pinging @pandorabot doesn't ping the respective account)
No one wants to have their stacks reduced in size, and even if the reduction has splitting benefits, can't we simply reduce the stack size manually ourselves?
MCLV 
you may have a hard time understanding a joke. and I understand that. I was merely pointing out the insignificance of a difference between 99 and 100, when there are much more useful numbers, although less, which would make more sense ;-)
Hedgehog
Stack size upgrade to 256?
Marsufoman
Yes please

**Comment by Klaranth** [comment]
Lots of conversations about : increasing stack size. Mostly undoable or lazyfying 
Use of the wrench removes need of high stack size.
