### ISSUE TITLE
Update bonemeal mod to support cactus and recent changes

### ISSUE THREAD

**Issue by eshattow** [pandorabox-io/in-game#51]
Mulch, fertilizer, do not appear to have an effect on cactus. Upstream commit pretty recent 1 month ago:
https://notabug.org/TenPlus1/bonemeal/commit/05e211a037f6486248493328645bf27669f9f4a9

**Comment by OgelGames** [comment]
We are already on the latest commit, and bonemeal/mulch/etc do work on both cactus and papyrus. Note that they must be on the correct nodes to grow, and the bonemeal/mulch must be applied to the bottom node.

Also, the code in that commit does nothing, as I mentioned here: https://github.com/pandorabox-io/pandorabox-mods/pull/1583
