### ISSUE TITLE
Reddit account 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#57]
Hedgehog : Close the reddit account. No one seems interested in using it.

**Comment by OgelGames** [comment]
If only we could, but it's "owned" by whoever this user is: https://www.reddit.com/user/aarsh_gandhi/

**Comment by Klaranth** [comment]
If it isn't Pandora's own, why not simply remove the link to it from the wiki front page?

If nobody knows about it ....

**Comment by OgelGames** [comment]
@BuckarooBanzay what's your opinion on removing the reddit link from the website? (and the Discord channel)

**Comment by BuckarooBanzay** [comment]
done and done :+1:
