### ISSUE TITLE
Create Twitch account

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#58]
Orekart's idea to run through some of the more dangerous minigames and streaming it on Twitch might be an interesting way to get more people interested in playing minetest in general and pandorabox in particular. 

Do we have players with experience on Twitch?

**Comment by OgelGames** [comment]
Well there is a Minetest category: https://www.twitch.tv/directory/game/Minetest

But if you mean like a specific pandorabox account, it doesn't work like that, it's more individuals that just pick a category and stream. (not that I've ever streamed, but I have used twitch)

**Comment by Klaranth** [comment]
From a Search Engine point of view, having several individuals linking all to one server means there is more hype to generate there.  Will look into how to stream and if my old Dell workhorse can take the role.

**Comment by S-S-X** [comment]
Other free options for streaming: YouTube, Restream, Dailymotion, Instagram, Facebook.

**Comment by OgelGames** [comment]
Closing due to not being related to Pandorabox or any specific feature or idea.
