### ISSUE TITLE
Minigame - Golden Palace easy access

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#73]
Hedgehog — 05/21/2021
Jacrackorn's golden palace .... how to add it to the minigame section? I have found no travelnet box on the island of the palace.
The place is at -2181 94 265.

orekart
Could add a mission stone

SX
Telemosaic at entrance (below it, on the ground). It is meant to be approached from below not from above. But good question would be what section it belongs to?
Also bad thing that I had to remove privilege access from minigames hub areas... it is supposed to be staff privilege protected but well, problems with areas... so protection bypass needed if someone would connect it before I'll be in game next time.

SX
Done.

**Comment by S-S-X** [comment]
Minigames Hub has telemosaic link leading to intended entrance path below golden palace. Nothing to do so this can be closed.
