### ISSUE TITLE
Question regarding Cannons

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#74]
int
can cannons be aimed?

SX
No but idea to allow aiming using digiline messages has been discussed before.

**Comment by Klaranth** [comment]
@S-S-X  @OgelGames 
As it hasn't been implemented after earlier discussions, can we safely close this today?

**Comment by S-S-X** [comment]
For this I think if someone comes up with good enough implementation it could be added. I think earlier discussions have been just in game chatting about ideas how aiming cannons could possibly be used but nobody opened tickets to space cannon project issue tracker.

**Interested in implementing or proving this would be useful:**
Head to https://github.com/pandorabox-io/spacecannon/issues and create issue there or open pull request that implements feature.

**Comment by Klaranth** [comment]
Will inform original poster (int) in-game to read this all and create issue at other repo.

**Comment by Klaranth** [comment]
Issue on space cannons created. This can now be closed.
