### ISSUE TITLE
Key access cards in-game

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#76]
orekart
I'd like to see key access cards (in-game item) be able to allow access to certain groups

Hedgehog
there is a mod for that
old mod ( 8+ years old ) : https://forum.minetest.net/viewtopic.php?t=3544

**Comment by Klaranth** [comment]
@S-S-X @OgelGames 

Come to think of it, isn't this already possible in-game by using protected / iron doors and handing out keys to them?  
Not so spiffy in space, but use space doors to the outside and iron doors once inside. 

So, decision time: Testing out an 8+ year old mod on the test server? 
Or, closing this issue now?

**Comment by S-S-X** [comment]
> I'd like to see key access cards (in-game item) be able to allow access to certain groups

Not sure what this actually means.
Is it about accessing single owned node like locked chest or is it about accessing larger protected area?

But yes, both can be done already. You can use keys or add players to protection. This feature sounds redundant because it can already be done with protections.

My personal opinion: functionality already exists and is not needed, not supporting this at all.
However if it is not about those use cases but about something else then better description is needed, some clarification about why this is needed and how it would useful and when it would be used.

**Comment by eshattow** [comment]
I agree the existing protection schemes are quite robust as-is. The use case for what I am describing is to allow for jumpdrive ships to dock in a protected space port, but limit this to players and ships that have a token (passcode, item, ?);  Also to not have to rely on a player owner of the protection area to always update and modify the area protection per-player but instead have access be scripted via lua mechanism. Strictly speaking there's no need to have an in-game item for this but similar to how the jumpdrive reads lua from a notebook for the saved co-ordinates that notebook and lua could stand-in for the keycard.

Another use case would be vending access to say rented areas: Receive a token good for some time period or as a reward from a mission, to gain access for an area.

I am not sure how this can be done already?

**Comment by Klaranth** [comment]
> Another use case would be vending access to say rented areas: Receive a token good for some time period or as a reward from a mission, to gain access for an area.
> 
> I am not sure how this can be done already?

Ehm, can the placing of an iron / protected door be automated? 
If that is the case, handing out keys to a door, that get replaced after x days .... 
Not sure how to deal with the keys, tho.

**Comment by S-S-X** [comment]
> I am not sure how this can be done already?

First case should be possible using playerfactions and handing out faction password. Jumpdrive protection check is buggy as it uses area mod protection check that does not work very well.
If player access has to be revoked it requires removing player from faction and changing password.
Very much related but not exactly same thing: https://github.com/pandorabox-io/pandorabox.io/issues/654

Second case asks for timer but not sure if that is good thing at all, renting panels that were made exactly for this were never really used. Some players have tried renting areas, it just does not seem to work.
There's been some success with selling prepared areas but that does not really happen often enough to require any automation.
This renting thing could be valid use case but I don't think it is useful in any way really...

For missions it is possible to temporarily grant some privileges to player and make area privilege protected, this would be a lot less complex way to handle missions and access expiration.
Currently admin only and needs some work to make privilege granting restricted and safe.

Currently you can build system that hands out area passwords after payment but you cannot remove access automatically.
Also I think it might be bad thing without some clear indicator that access will be only temporary, missions sounds like good way to handle this.

@eshattow how do you see it, would fixing jumpdrive protection checks and using factions be good enough for first case?
About second case with expiration timers (renting, missions) does using missions sound good enough if already possible?
(both still need some in game testing, not sure what actually works and what does not)

**Comment by eshattow** [comment]
I will need to also test to see if this can be done now.

**Comment by eshattow** [comment]
We're now encountering the jumpdrive protection check problems for the player faction, so that needs a fix and then more testing can happen.

**Comment by S-S-X** [comment]
> We're now encountering the jumpdrive protection check problems for the player faction, so that needs a fix and then more testing can happen.

Related: https://github.com/pandorabox-io/pandorabox.io/issues/654 and also #127
