### ISSUE TITLE
Adjusting itemstack infotext (shared anvil)

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#78]
rekart
shared anvil (anvil + paper -> shared anvil) does not say shared anvil in the recipes and doesn't show up when searching for shared

SX
Feature request to support description/infotext correctly: minetest-mods/unified_inventory#165
This would fix shared anvil. Search might also require changes to take metadata infotext into account but not sure.

Crafting and guide: Display itemstack infotext for craft output · If crafting recipe output stack has infotext display it for stack in craft output slot. Also if infotext is available display it instead of description in crafting guide.

**Comment by S-S-X** [comment]
Discussion about this should continue on implementation ticket.
