### ISSUE TITLE
Mail system upgrades

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#83]
orekart : The in-game mail system lacks a sent-button. 
Hedgehog : Put your own name in CC 
OgelGames : Open issue for an outbox for mail: pandorabox-io/pandorabox.io#614
SX : https://github.com/minetest-mail/mail_mod/issues/14

**Comment by OgelGames** [comment]
Closing in favor of the other issues.

**Comment by Klaranth** [comment]
Vamp ; Hedgehog ; SX 

Timestamp for emails for both sent and received emails
Timestamp or just date received?

Timestamps are already in backend, just not visible in game. See https://pandorabox.io/webmail

It would be good to have email timestamps in-game too :)

Basically should be enough to simply add timestamp to mail form

**Comment by Klaranth** [comment]
Hedgehog 
/mute can mute a player's texts and msg, but is there a way to stop /mail from folks?

**Comment by OgelGames** [comment]
Mail outbox was added in https://github.com/mt-mods/mail/pull/26. I've added the other suggestion to https://github.com/mt-mods/mail/issues/102. Closing this.
