### ISSUE TITLE
Usage of /pm and /dm alongside /msg 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#85]
orekart 
In short order, beerchat needs an alias added /pm --> /msg
/pm and /dm should both alias to /msg

OgelGames
it should be quite easy to add /pm and /dm as alternates to /msg
Just add /pm and /dm commands that call the same function that /msg does

**Comment by S-S-X** [comment]
Implementation discussion moved on to linked ticket so this can be closed. Idea already has possible implementation.
