### ISSUE TITLE
Restricting new usernames 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#87]
1hit 
Disallow the creation of any username that is >= 50% capital letters or numbers.
It's jarring to the mind to see that much all caps.  Maybe the ratio can be changed, or the rule be "no user names w/ >4 cap letters".  I don't know, but would like to see the prevention of "all caps user names".

Existing names are permitted (FeXoR).

Motivation: DA_KING, MYSTERIOUS, etc

**Comment by Klaranth** [comment]
orekart
I think 4-in-a-row numbers or capital letters should just show as "unavailable" to register.

**Comment by S-S-X** [comment]
* `minetest.register_on_prejoinplayer(function(name, ip))`
    * Called when a client connects to the server, prior to authentication
    * If it returns a string, the client is disconnected with that string as
      reason.

This can probably be done by simply registering on_prejoinplayer handler similar to default handler which looks like this:
```lua
core.register_on_prejoinplayer(function(name, ip)
	if core.registered_auth_handler ~= nil then
		return -- Don't do anything if custom auth handler registered
	end
	local auth_entry = core_auth.read(name)
	if auth_entry ~= nil then
		return
	end

	local name_lower = name:lower()
	for k in core.builtin_auth_handler.iterate() do
		if k:lower() == name_lower then
			return string.format("\nCannot create new player called '%s'. "..
					"Another account called '%s' is already registered. "..
					"Please check the spelling if it's your account "..
					"or use a different nickname.", name, k)
		end
	end
end)
```

**Comment by OgelGames** [comment]
Coding it is not the hard part, the hard part is deciding what exactly should be disallowed.

I was thinking something like, no more than 4 capital letters, and no more than 50% numbers or special characters (`-` or `_`). That would allow most names, but stop names like `0123456789`, `---mike---`, `MINETESTEXE`, etc. (all those are actual usernames BTW)

And the code would be something like this: (not tested)
```lua
local function count(str, pat)
    return select(2, string.gsub(str, pat, ""))
end

core.register_on_prejoinplayer(function(name, ip)
	if count(name, "%u") > 4 then
		return "Username contains too many capital letters"
	end
	if count(name, "%A") > name:len() / 2 then
		return "Username contains too many non-letter characters"
	end
end)
```

**Comment by S-S-X** [comment]
> the hard part is deciding what exactly should be disallowed.

I disagree with that, require at least single alphabet a-Z and apply rule to have at least 50% alphabets a-Z and at least 50% of those lower case, rest of it can be numbers, underscores or dashes.
It is not very strict which is good but strict enough to block worst names.

Decision only becomes hard if you try too much like start thinking what can be done to intentionally get around simple barrier to obtain in game name that is not fine. However there's additional barrier which is removing player with not so nice name, I think I've done this twice, it works fine and I don't think it really needs any automation.

> And the code would be something like this: (not tested)

Add check if authentication data exists `get_auth_handler().get.auth(name)`

**Comment by OgelGames** [comment]
> require at least single alphabet a-Z and apply rule to have at least 50% alphabets a-Z and at least 50% of those lower case, rest of it can be numbers, underscores or dashes.

What about names like `SX`, `FeXoR` or `3C`, those IMO are perfectly fine names, but would be blocked by those rules.

**Comment by S-S-X** [comment]
> > require at least single alphabet a-Z and apply rule to have at least 50% alphabets a-Z and at least 50% of those lower case, rest of it can be numbers, underscores or dashes.
> 
> What about names like `SX`, `FeXoR` or `3C`, those IMO are perfectly fine names, but would be blocked by those rules.

True, 50% requirement is too high and very short names should not be checked for other than having at least one alphabet character. As goal is to disallow mostly all caps or all punctuation names it would fine to let shorter than 6 character names through checking only for at least single alphabet and for everything else drop lowercase requirement to some 20%.

**Comment by S-S-X** [comment]
It would probably be better to allow bypass by returning message with warning about possibly bad name and asking to register again. Second attempt with exactly same name would then allow account creation without further complaints.
After that let moderators make decision, mod channel notification could also be added.

**Comment by S-S-X** [comment]
I don't think this needs to stay open: while certain player names have caused troubles in chat few times it does not really need tech solution. Does not happen that often and moderator toolbox already contains everything needed to fix any real issues.
