### ISSUE TITLE
Translation of displayed text in-game

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#89]
SX 
Is it possible to translate text displayed on signs in-game.
Minetest has builtin system for translating texts, just not sure if it works with things like signs... I know it wont work with some signs but it might be possible depending on how text is actually rendered (I mean if it happens server side vs client side).

Examples for translation if someone interested:
Old:
https://github.com/mt-mods/technic/blob/master/technic/locale/de.txt 
New: https://github.com/louisroyer/minetest-technic/blob/locale-mt5/technic/locale/technic.de.tr

And weblate projects: https://hosted.weblate.org/projects/minetest/

**Comment by OgelGames** [comment]
All signs render text with entities, using textures that are part of the mods, so it's not possible to show different entities to different players.

The text inside posters *could* be translated, but the built-in translation system is not dynamic, it requires all text to be pre-translated, so it would be very difficult to implement in a usable way, if at all.

**Comment by S-S-X** [comment]
> The text inside posters could be translated, but the built-in translation system is not dynamic, it requires all text to be pre-translated, so it would be very difficult to implement in a usable way, if at all.

Idea I had was not to actually translate signs written by players but translate some mod provided signs where content is known and translations are provided to clients by server similar how it happens currently. Actually idea came from this #88 
But if all signs are always sent as textures and entities cannot draw translated text client side then this is not really possible at all.

**Comment by Klaranth** [comment]
CadViper 
I wonder if it would be possible to implement Google translate into a Minetest mod... then we would not need multiple language channels.
It is probably a dumb idea, but I wonder what the feasibility would be.

SX 
Possible but not really good idea. Simple translators like that can't handle context and can't translate even simple typos which sometimes lead into completely different translations. Some AI that understands context, for example ChatGPT, could do it. But even then it probably shouldn't be server side mod but all client side (and while you can do this it isn't as easy for end users).

**Comment by Klaranth** [comment]
See also #84.

The4spaceconstants 
Use this : https://content.minetest.net/packages/Droog71/chat_translator/

SX 
Looks nice but probably requires some additional work to make it fully compatible with beerchat.
