### ISSUE TITLE
World management privileges to high XP players 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#93]
orekart
XP Award for reaching 2 million XP : Ability to remove others' travelnet boxes and owned items

SX 
Big NO
Some high XP players cause problems even without extra privileges. XP cannot be used to grant world management privileges, those have to be earned some other way, that could include some form of voting possibly but not XP, dig count, punch count, craft count, play time, discord message count or anything like that.

Basic idea about granting privileges like that however is interesting, just have to find way to actually select trusted and nice players who are able to think first and who are not going to use power to manage other players stuff for personal advantages.

It is similar to protect_streets which is granted to players when needed, many actually have that privilege and it allows access to many public areas. Managing other players owned things would be something similar but bit higher permission.

specing :  Can you jump someone else's tnet/locked chests away?

SX  : Should be possible if not protected

Test_User : Did it once when someone left locked chests in my jd that I needed to... get rid of

Hedgehog : 1hit did a test a while ago with different chests and space cannons.  I wonder what happens to Tnetboxes when space cannons are used on them ....

OgelGames 
They should be invincible because of this check: https://github.com/pandorabox-io/spacecannon/blob/master/util.lua#L101

1hittoaster : Locked chests w/ items in were destroyed by direct cannon fire.  I did not test firing against travelnets.
If they are invulnerable, then one could armor their ship in them.

**Comment by OgelGames** [comment]
I agree with SX:
> Big NO

And judging by the reaction to SX's comment on discord, BuckarooBanzai agrees too.

I'd say this can be closed.

**Comment by S-S-X** [comment]
To clarify a bit:
I would not be against basic idea of having such privileges available, only against granting those privileges based on player xp.

However I've not heard about many problems. Also I've done some cleanup in few areas (around towns) removing some old protectors placed by player who never built anything there but basically just blocked plots with protectors or other owned items like locked chests or anvils.

Currently if there's situation where cleanup is actually needed players can contact any moderator, explain situation and why things owned by other players should be removed.

I think this extra access level to remove owned nodes can be considered if it seems that there's really need for it, basically if moderators receive significant amount of these cleanup requests. So far I've not seen that many requests (valid or invalid).
