### ISSUE TITLE
 Node-breaker to speak digiline

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#95]
Check #81 for earlier discussion on CLU and Digiline updates on machines.

@dennisjenkins75 
I would very much like to see the node-breaker and node-deployer capable to speaking digiline. Its cumbersome to have an almost pure-digiline machine that needs digiline<->mesecons interface to use these machines.

@S-S-X
In my opinion adding digiline interface for devices that currently accept mesecons signal (for basic on/off control) would be fine if digiline control allows exactly same binary functions like "enable", "disable" and possibly "activate" (last one being similar to mesecons on/off pulse action, maybe there's better word for that...).

If adding more advanced functionality than what mesecons can practically provide with binary input then it depends on actual functionality added, there's no generic "one size fits all" answer. In this case it should be separate discussion for each device.

**Comment by eshattow** [comment]
Proposed: Add the capability to connect with digiline and digiline conducting pneumatic tubes, query the node-breaker for its inventory slot contents, and activate it.

Formspec changes:
node-breaker add a channel text-box / set-button / close-button.

Usage to query:
digiline_send("nbchan","GET")
digiline_send("nbchan",{command="get"})

query response:
{
  msg {
    name == "foo:bar",
    count == n
  }
  channel == "nbchan"
  type == "digiline"
}

Usage to activate:
digiline_send("nbchan","")
digiline_send("nbchan",{})

There is no parity for mesecons signal holding the state high/low, as the node-breaker is simulating a fake player anyways so there is no "high/low" state; digging has no half-way state.

It might be useful to ignore mesecons input signals however, depending on the machine for example placing a node detector adjacent to a nodedetector. This could be as an upgraded digilines-only nodebreaker, or a configurable setting.

I don't know how to code it but that sounds simple enough right?

**Comment by S-S-X** [comment]
> The reason in favor of a separate digiline-specific node-breaker would be to retain the node-detector adjacent in placement to a node-breaker yet have it be digiline operated and not subject to unwanted mesecons signals from the node-detector.

You can also disable detector mesecons output signals. I mean you can do this now without any changes if you use detector only with digiline queries.

**Comment by eshattow** [comment]
> You can also disable detector mesecons output signals. I mean you can do this now without any changes if you use detector only with digiline queries.

Yes but then there is the loss of command="scan". Supply converter has an option "Ignoring Mesecon Signal" for example.

The mesecons piston has a specific digiline version as the Digilines Piston from digistuff mod, presumably because it combines the functionality of both piston and sticky piston. If there were a combination of node breaker and deployer (Left Mouse Button action and Right Mouse Button action) would that make sense or is there some play test reason why to keep those actions as two different machines? If it should be a new combined function machine then it would be a new mod item, otherwise focus on getting the basic digiline functionality upstream so it benefits the most players.

**Comment by S-S-X** [comment]
> If there were a combination of node breaker and deployer (Left Mouse Button action and Right Mouse Button action)

There is technic constructor that does some jobs that both do but still very different, it does not operate tools and does not trigger normal dig/place callbacks.

> would that make sense or is there some play test reason why to keep those actions as two different machines?

There is reason to not reimplement/copy fake player stuff done by pipeworks and of course also basic operations as it is bit complicated thing overall for keeping it up to date as separate mod, that would be one reason to attempt keeping it in pipeworks whatever it would be in the end. Or at least use pipeworks implementation if that's possible.
Pipeworks already has a lot of users and through that also good support.
