### ISSUE TITLE
Starting inventory

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#99]
Vamp: 
Can new players start the game with 1 protector in inventory?

SX (& Thinksome)   
Crafting protector takes one gold ingot and 8 stones, beginner can easily get that as first item either by spending some starting money or by simply digging up gold in public mines. Also can buy protectors as many players do sell those.

**Comment by S-S-X** [comment]
I'd be against this addition, if player is going to stay and play even little bit it is very simple task to craft protectors.
If player is not going to actually play but just mess around a bit and leave then giving protector as starting item is very bad idea.

**Comment by Klaranth** [comment]
In light of the most recent comment, I close this issue.
